/* ==========================================================================
   Comparely — Product Database
   150 sample products across 5 categories: Smartphones, Laptops,
   Headphones, Smartwatches, Tablets. Illustrative sample data, not live
   pricing. Every product includes MSRP, release year, average rating,
   review count, key features, detailed specifications, pros, and cons.
   Spec keys are kept consistent within each category so the comparison
   engine in script.js can determine a fair per-row winner.
   ========================================================================== */

const PRODUCTS = [

/* ---------------------------- Smartphones (1–35) ---------------------------- */
{ id: 1, name: 'iPhone 13', brand: 'Apple', category: 'Smartphones', year: 2021, price: 599, rating: 4.5, reviews: 28450,
  features: ['A15 Bionic chip', 'Cinematic mode video', 'Ceramic Shield front', 'Dual-camera system'],
  pros: ['Still fast for daily use', 'Great value now', 'Compact, comfortable size'],
  cons: ['Only 60Hz display', 'Camera system trails newer Pro models'],
  specs: { Display: '6.1" OLED', Processor: 'A15 Bionic', RAM: '4GB', Storage: '128GB', Battery: '3240 mAh', 'Rear Camera': '12MP Dual', Weight: '174g', '5G': 'Yes' } },
{ id: 2, name: 'iPhone 13 Pro', brand: 'Apple', category: 'Smartphones', year: 2021, price: 749, rating: 4.6, reviews: 19870,
  features: ['ProMotion 120Hz display', 'Triple-camera with telephoto', 'Macro photography', 'LiDAR scanner'],
  pros: ['Buttery-smooth ProMotion display', 'Excellent low-light photos', 'Solid battery life'],
  cons: ['Heavier than the standard 13', 'No USB-C'],
  specs: { Display: '6.1" OLED 120Hz', Processor: 'A15 Bionic', RAM: '6GB', Storage: '128GB', Battery: '3095 mAh', 'Rear Camera': '12MP Triple', Weight: '204g', '5G': 'Yes' } },
{ id: 3, name: 'iPhone 14', brand: 'Apple', category: 'Smartphones', year: 2022, price: 699, rating: 4.5, reviews: 21230,
  features: ['Crash detection', 'Action mode stabilization', 'Improved low-light camera', 'Satellite emergency SOS'],
  pros: ['Reliable everyday performance', 'Strong low-light camera for the price', 'Good battery life'],
  cons: ['Same design as the 13', 'Still 60Hz refresh rate'],
  specs: { Display: '6.1" OLED', Processor: 'A15 Bionic', RAM: '6GB', Storage: '128GB', Battery: '3279 mAh', 'Rear Camera': '12MP Dual', Weight: '172g', '5G': 'Yes' } },
{ id: 4, name: 'iPhone 14 Pro', brand: 'Apple', category: 'Smartphones', year: 2022, price: 899, rating: 4.7, reviews: 24560,
  features: ['Dynamic Island', 'Always-On display', '48MP main sensor', 'A16 Bionic chip'],
  pros: ['Dynamic Island is genuinely useful', 'Big camera resolution jump', 'Excellent build quality'],
  cons: ['Premium pricing', 'Always-On display drains battery faster'],
  specs: { Display: '6.1" OLED 120Hz', Processor: 'A16 Bionic', RAM: '6GB', Storage: '128GB', Battery: '3200 mAh', 'Rear Camera': '48MP Triple', Weight: '206g', '5G': 'Yes' } },
{ id: 5, name: 'iPhone 15', brand: 'Apple', category: 'Smartphones', year: 2023, price: 799, rating: 4.6, reviews: 17890,
  features: ['USB-C charging', 'Dynamic Island', '48MP main camera', 'Colour-infused glass back'],
  pros: ['USB-C finally arrives', 'Sharper photos than the 14', 'Comfortable, lighter build'],
  cons: ['Still capped at 60Hz', 'A16 chip is a generation behind Pro'],
  specs: { Display: '6.1" OLED', Processor: 'A16 Bionic', RAM: '6GB', Storage: '128GB', Battery: '3349 mAh', 'Rear Camera': '48MP Dual', Weight: '171g', '5G': 'Yes' } },
{ id: 6, name: 'iPhone 15 Pro', brand: 'Apple', category: 'Smartphones', year: 2023, price: 999, rating: 4.7, reviews: 15243,
  features: ['Titanium design', 'A17 Pro chip', 'Action Button', 'USB-C with USB 3 speeds'],
  pros: ['Best-in-class performance', 'Excellent camera system', 'Premium titanium build'],
  cons: ['Expensive', 'No charger included'],
  specs: { Display: '6.1" OLED 120Hz', Processor: 'A17 Pro', RAM: '8GB', Storage: '128GB', Battery: '3274 mAh', 'Rear Camera': '48MP Triple', Weight: '187g', '5G': 'Yes' } },
{ id: 7, name: 'iPhone 16', brand: 'Apple', category: 'Smartphones', year: 2024, price: 829, rating: 4.6, reviews: 9120,
  features: ['Camera Control button', 'A18 chip', 'Dedicated Action Button', 'Apple Intelligence support'],
  pros: ['Meaningful performance jump', 'New camera control is handy', 'Great battery life'],
  cons: ['Apple Intelligence rolls out gradually', 'Design largely unchanged'],
  specs: { Display: '6.1" OLED', Processor: 'A18', RAM: '8GB', Storage: '128GB', Battery: '3561 mAh', 'Rear Camera': '48MP Dual', Weight: '170g', '5G': 'Yes' } },
{ id: 8, name: 'iPhone 16 Pro', brand: 'Apple', category: 'Smartphones', year: 2024, price: 1099, rating: 4.8, reviews: 8460,
  features: ['Larger display', 'A18 Pro chip', 'Camera Control button', '5x telephoto lens'],
  pros: ['Best telephoto zoom yet', 'Bigger, more immersive screen', 'Top-tier build quality'],
  cons: ['Among the priciest phones on the market', 'Larger size is less pocketable'],
  specs: { Display: '6.3" OLED 120Hz', Processor: 'A18 Pro', RAM: '8GB', Storage: '256GB', Battery: '3582 mAh', 'Rear Camera': '48MP Triple', Weight: '199g', '5G': 'Yes' } },
{ id: 9, name: 'iPhone SE (3rd gen)', brand: 'Apple', category: 'Smartphones', year: 2022, price: 429, rating: 4.3, reviews: 11200,
  features: ['Touch ID home button', 'A15 Bionic chip', 'Compact classic design', 'Water resistant'],
  pros: ['Most affordable way into iOS', 'Small, one-hand-friendly size', 'Fast chip for the price'],
  cons: ['Dated design with thick bezels', 'Single camera limits versatility'],
  specs: { Display: '4.7" LCD', Processor: 'A15 Bionic', RAM: '4GB', Storage: '64GB', Battery: '2018 mAh', 'Rear Camera': '12MP Single', Weight: '144g', '5G': 'Yes' } },
{ id: 10, name: 'Samsung Galaxy S22', brand: 'Samsung', category: 'Smartphones', year: 2022, price: 699, rating: 4.3, reviews: 9870,
  features: ['120Hz adaptive display', 'Triple camera array', 'IP68 rating', 'Fast 25W charging'],
  pros: ['Compact flagship footprint', 'Vivid AMOLED screen', 'Smooth performance'],
  cons: ['Battery is on the smaller side', 'Charging trails rivals'],
  specs: { Display: '6.1" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 1', RAM: '8GB', Storage: '128GB', Battery: '3700 mAh', 'Rear Camera': '50MP Triple', Weight: '168g', '5G': 'Yes' } },
{ id: 11, name: 'Samsung Galaxy S23', brand: 'Samsung', category: 'Smartphones', year: 2023, price: 799, rating: 4.5, reviews: 10430,
  features: ['Snapdragon 8 Gen 2 for Galaxy', 'Improved low-light selfie camera', 'Gorilla Glass Victus 2', 'Vision Booster display'],
  pros: ['Excellent one-hand size', 'Reliable all-day battery', 'Consistently smooth performance'],
  cons: ['Base storage is limited', 'Charging speed still modest'],
  specs: { Display: '6.1" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 2', RAM: '8GB', Storage: '128GB', Battery: '3900 mAh', 'Rear Camera': '50MP Triple', Weight: '168g', '5G': 'Yes' } },
{ id: 12, name: 'Samsung Galaxy S23 Ultra', brand: 'Samsung', category: 'Smartphones', year: 2023, price: 1199, rating: 4.6, reviews: 13980,
  features: ['Built-in S Pen', '200MP main sensor', '10x optical zoom', 'Integrated stylus silo'],
  pros: ['Best-in-class zoom camera', 'S Pen adds real utility', 'Long-lasting battery'],
  cons: ['Large and heavy', 'Premium price'],
  specs: { Display: '6.8" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 2', RAM: '12GB', Storage: '256GB', Battery: '5000 mAh', 'Rear Camera': '200MP Quad', Weight: '234g', '5G': 'Yes' } },
{ id: 13, name: 'Samsung Galaxy S24', brand: 'Samsung', category: 'Smartphones', year: 2024, price: 799, rating: 4.5, reviews: 8210,
  features: ['Galaxy AI features', 'Circle to Search', '7 years of OS updates', 'Titanium-look frame'],
  pros: ['Long software support commitment', 'Genuinely useful AI tools', 'Compact flagship option'],
  cons: ['Charging speed still modest', 'Base RAM could be more generous'],
  specs: { Display: '6.2" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 3', RAM: '8GB', Storage: '128GB', Battery: '4000 mAh', 'Rear Camera': '50MP Triple', Weight: '167g', '5G': 'Yes' } },
{ id: 14, name: 'Samsung Galaxy S24 Ultra', brand: 'Samsung', category: 'Smartphones', year: 2024, price: 1299, rating: 4.6, reviews: 12876,
  features: ['Built-in S Pen', '200MP camera', 'Titanium frame', 'AI-powered photo editing'],
  pros: ['Gorgeous display', 'Versatile camera system', 'Long software support'],
  cons: ['Premium price', 'Large size may not suit everyone'],
  specs: { Display: '6.8" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 3', RAM: '12GB', Storage: '256GB', Battery: '5000 mAh', 'Rear Camera': '200MP Quad', Weight: '232g', '5G': 'Yes' } },
{ id: 15, name: 'Samsung Galaxy A55', brand: 'Samsung', category: 'Smartphones', year: 2024, price: 449, rating: 4.2, reviews: 5230,
  features: ['AMOLED display at a mid-range price', 'IP67 rating', 'Large 5000mAh battery', 'Metal frame'],
  pros: ['Excellent value for the display quality', 'All-day battery life', 'Durable build for the price'],
  cons: ['Performance lags true flagships', 'Slower charging speed'],
  specs: { Display: '6.6" AMOLED 120Hz', Processor: 'Exynos 1480', RAM: '8GB', Storage: '128GB', Battery: '5000 mAh', 'Rear Camera': '50MP Triple', Weight: '213g', '5G': 'Yes' } },
{ id: 16, name: 'Google Pixel 7', brand: 'Google', category: 'Smartphones', year: 2022, price: 599, rating: 4.4, reviews: 8760,
  features: ['Tensor G2 chip', 'Magic Eraser', 'Face unlock', 'Clean Android experience'],
  pros: ['Excellent photos for the price', 'Clean, bloat-free software', 'Strong value flagship'],
  cons: ['90Hz instead of 120Hz', 'Tensor chip runs warm under load'],
  specs: { Display: '6.3" OLED 90Hz', Processor: 'Tensor G2', RAM: '8GB', Storage: '128GB', Battery: '4355 mAh', 'Rear Camera': '50MP Dual', Weight: '197g', '5G': 'Yes' } },
{ id: 17, name: 'Google Pixel 7 Pro', brand: 'Google', category: 'Smartphones', year: 2022, price: 899, rating: 4.5, reviews: 6540,
  features: ['5x telephoto lens', '120Hz LTPO display', 'Tensor G2 chip', 'Real-time translation'],
  pros: ['Best zoom in the Pixel lineup at the time', 'Smooth adaptive display', 'Excellent computational photography'],
  cons: ['Battery life is average', 'Large footprint'],
  specs: { Display: '6.7" OLED 120Hz', Processor: 'Tensor G2', RAM: '12GB', Storage: '128GB', Battery: '5000 mAh', 'Rear Camera': '50MP Triple', Weight: '212g', '5G': 'Yes' } },
{ id: 18, name: 'Google Pixel 8', brand: 'Google', category: 'Smartphones', year: 2023, price: 699, rating: 4.5, reviews: 7120,
  features: ['Best Take group photos', '7 years of OS updates', 'Tensor G3 chip', 'Compact flagship size'],
  pros: ['Long update commitment', 'Excellent camera processing', 'More compact than the Pro'],
  cons: ['Only two rear cameras', 'Charging speed is modest'],
  specs: { Display: '6.2" OLED 120Hz', Processor: 'Tensor G3', RAM: '8GB', Storage: '128GB', Battery: '4575 mAh', 'Rear Camera': '50MP Dual', Weight: '187g', '5G': 'Yes' } },
{ id: 19, name: 'Google Pixel 8 Pro', brand: 'Google', category: 'Smartphones', year: 2023, price: 999, rating: 4.5, reviews: 8341,
  features: ['Magic Editor AI tools', '7 years of OS updates', 'Temperature sensor', 'Clean Android experience'],
  pros: ['Best computational photography', 'Clean software experience', 'Long update commitment'],
  cons: ['Battery life is average', 'Tensor chip runs warm'],
  specs: { Display: '6.7" OLED 120Hz', Processor: 'Tensor G3', RAM: '12GB', Storage: '128GB', Battery: '5050 mAh', 'Rear Camera': '50MP Triple', Weight: '213g', '5G': 'Yes' } },
{ id: 20, name: 'Google Pixel 9 Pro', brand: 'Google', category: 'Smartphones', year: 2024, price: 999, rating: 4.6, reviews: 4210,
  features: ['Tensor G4 chip', 'Gemini AI assistant built-in', 'Add Me photo tool', '7 years of updates'],
  pros: ['Genuinely helpful on-device AI', 'Refined camera hardware', 'Class-leading software support'],
  cons: ['Premium pricing', 'Battery life still just average'],
  specs: { Display: '6.3" OLED 120Hz', Processor: 'Tensor G4', RAM: '16GB', Storage: '128GB', Battery: '4700 mAh', 'Rear Camera': '50MP Triple', Weight: '199g', '5G': 'Yes' } },
{ id: 21, name: 'OnePlus 11', brand: 'OnePlus', category: 'Smartphones', year: 2023, price: 699, rating: 4.4, reviews: 5210,
  features: ['Hasselblad camera tuning', '100W fast charging', 'Alert Slider', '120Hz LTPO display'],
  pros: ['Charges fully in under 30 minutes', 'Flagship specs below flagship price', 'Smooth, responsive software'],
  cons: ['No official IP68 rating in all markets', 'Camera trails top rivals in low light'],
  specs: { Display: '6.7" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 2', RAM: '16GB', Storage: '256GB', Battery: '5000 mAh', 'Rear Camera': '50MP Triple', Weight: '205g', '5G': 'Yes' } },
{ id: 22, name: 'OnePlus 12', brand: 'OnePlus', category: 'Smartphones', year: 2024, price: 799, rating: 4.4, reviews: 6120,
  features: ['100W fast charging', 'Hasselblad camera tuning', 'Alert Slider', '120Hz LTPO display'],
  pros: ['Blazing fast charging', 'Flagship specs for less', 'Smooth 120Hz display'],
  cons: ['Software has occasional bugs', 'Wireless charging not available in all markets'],
  specs: { Display: '6.82" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 3', RAM: '16GB', Storage: '256GB', Battery: '5400 mAh', 'Rear Camera': '50MP Triple', Weight: '220g', '5G': 'Yes' } },
{ id: 23, name: 'OnePlus 12R', brand: 'OnePlus', category: 'Smartphones', year: 2024, price: 499, rating: 4.3, reviews: 3980,
  features: ['100W fast charging', 'Massive 5500mAh battery', 'Snapdragon 8 Gen 2', 'Aqua Touch wet-screen support'],
  pros: ['Outstanding value for a near-flagship chip', 'Huge battery easily lasts two days', 'Very fast charging'],
  cons: ['Camera versatility trails the standard 12', 'Plastic-feeling frame'],
  specs: { Display: '6.78" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 2', RAM: '16GB', Storage: '256GB', Battery: '5500 mAh', 'Rear Camera': '50MP Dual', Weight: '207g', '5G': 'Yes' } },
{ id: 24, name: 'Nothing Phone (2)', brand: 'Nothing', category: 'Smartphones', year: 2023, price: 599, rating: 4.3, reviews: 4120,
  features: ['Glyph lighting interface', 'Transparent design', 'Nothing OS', '45W fast charging'],
  pros: ['Genuinely distinctive design', 'Clean, near-stock Android software', 'Solid all-around performance'],
  cons: ['Glyph interface is more novelty than necessity', 'Camera is good but not class-leading'],
  specs: { Display: '6.7" OLED 120Hz', Processor: 'Snapdragon 8+ Gen 1', RAM: '8GB', Storage: '128GB', Battery: '4700 mAh', 'Rear Camera': '50MP Dual', Weight: '201g', '5G': 'Yes' } },
{ id: 25, name: 'Nothing Phone (2a)', brand: 'Nothing', category: 'Smartphones', year: 2024, price: 349, rating: 4.2, reviews: 2870,
  features: ['Glyph lighting interface', 'Budget-friendly transparent design', 'Large 5000mAh battery', '45W charging'],
  pros: ['Striking design at a budget price', 'Long-lasting battery', 'Smooth 120Hz AMOLED display'],
  cons: ['Mid-range chip limits gaming performance', 'Plastic build feels less premium'],
  specs: { Display: '6.7" AMOLED 120Hz', Processor: 'Dimensity 7200 Pro', RAM: '8GB', Storage: '128GB', Battery: '5000 mAh', 'Rear Camera': '50MP Dual', Weight: '190g', '5G': 'Yes' } },
{ id: 26, name: 'Motorola Edge 50 Pro', brand: 'Motorola', category: 'Smartphones', year: 2024, price: 599, rating: 4.2, reviews: 1980,
  features: ['125W TurboPower charging', 'Curved pOLED display', 'IP68 rating', 'Wireless charging included'],
  pros: ['Charges from empty in about 20 minutes', 'Generous storage at this price', 'Premium curved-glass design'],
  cons: ['Chipset is mid-range despite the flagship-like price', 'Bloatware in some regions'],
  specs: { Display: '6.7" pOLED 144Hz', Processor: 'Snapdragon 7 Gen 3', RAM: '12GB', Storage: '512GB', Battery: '4500 mAh', 'Rear Camera': '50MP Triple', Weight: '186g', '5G': 'Yes' } },
{ id: 27, name: 'Motorola Razr 40 Ultra', brand: 'Motorola', category: 'Smartphones', year: 2023, price: 999, rating: 4.1, reviews: 2340,
  features: ['Large 3.6" external cover screen', 'Foldable flip design', '165Hz main display', 'IP52 splash resistance'],
  pros: ['Cover screen is genuinely usable', 'Compact when folded', 'Distinctive, pocketable design'],
  cons: ['Battery life suffers with heavy cover-screen use', 'Camera is modest for the price'],
  specs: { Display: '6.9" pOLED 165Hz', Processor: 'Snapdragon 8+ Gen 1', RAM: '8GB', Storage: '256GB', Battery: '3800 mAh', 'Rear Camera': '12MP Dual', Weight: '188g', '5G': 'Yes' } },
{ id: 28, name: 'Moto G Power', brand: 'Motorola', category: 'Smartphones', year: 2023, price: 299, rating: 4.0, reviews: 3450,
  features: ['Multi-day battery life', '120Hz refresh rate at a budget price', 'Water-repellent design', 'Expandable storage'],
  pros: ['Battery genuinely lasts two-plus days', 'Smooth scrolling for the price', 'Affordable 5G option'],
  cons: ['Camera struggles in low light', 'Performance limited for demanding apps'],
  specs: { Display: '6.5" LCD 120Hz', Processor: 'Snapdragon 695', RAM: '4GB', Storage: '128GB', Battery: '5000 mAh', 'Rear Camera': '50MP Dual', Weight: '200g', '5G': 'Yes' } },
{ id: 29, name: 'Xiaomi 13T Pro', brand: 'Xiaomi', category: 'Smartphones', year: 2023, price: 649, rating: 4.3, reviews: 3120,
  features: ['Leica-tuned optics', '120W HyperCharge', '144Hz AMOLED display', 'IP68 rating'],
  pros: ['Charges fully in about 19 minutes', 'Excellent Leica camera tuning', 'Flagship performance for less'],
  cons: ['HyperOS software has a learning curve', 'Limited availability outside key markets'],
  specs: { Display: '6.67" AMOLED 144Hz', Processor: 'Dimensity 9200+', RAM: '12GB', Storage: '256GB', Battery: '5000 mAh', 'Rear Camera': '50MP Triple', Weight: '200g', '5G': 'Yes' } },
{ id: 30, name: 'Xiaomi 14 Pro', brand: 'Xiaomi', category: 'Smartphones', year: 2024, price: 749, rating: 4.3, reviews: 4532,
  features: ['Leica optics', '90W wired charging', 'IP68 rating', 'HyperOS'],
  pros: ['Excellent value for the specs', 'Fast charging', 'Sharp Leica camera tuning'],
  cons: ['HyperOS has a learning curve', 'Limited availability in some regions'],
  specs: { Display: '6.73" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 3', RAM: '12GB', Storage: '256GB', Battery: '4880 mAh', 'Rear Camera': '50MP Triple', Weight: '223g', '5G': 'Yes' } },
{ id: 31, name: 'Redmi Note 13 Pro', brand: 'Xiaomi', category: 'Smartphones', year: 2024, price: 299, rating: 4.1, reviews: 6780,
  features: ['200MP main camera', '67W fast charging', 'Curved AMOLED display', 'IP54 splash resistance'],
  pros: ['Remarkable camera resolution for the price', 'Excellent display quality for a budget phone', 'Strong all-day battery'],
  cons: ['MIUI/HyperOS bloatware out of the box', 'Plastic build quality'],
  specs: { Display: '6.67" AMOLED 120Hz', Processor: 'Dimensity 7200 Ultra', RAM: '8GB', Storage: '256GB', Battery: '5100 mAh', 'Rear Camera': '200MP Triple', Weight: '187g', '5G': 'Yes' } },
{ id: 32, name: 'ASUS ROG Phone 8', brand: 'ASUS', category: 'Smartphones', year: 2024, price: 1099, rating: 4.4, reviews: 1560,
  features: ['165Hz gaming display', 'AirTrigger shoulder buttons', 'Front-facing stereo speakers', 'GameCool vapor chamber cooling'],
  pros: ['Best-in-class gaming performance', 'Shoulder triggers are genuinely useful', 'Excellent sustained performance under load'],
  cons: ['Bulkier than typical flagships', 'Gaming-first design is not for everyone'],
  specs: { Display: '6.78" AMOLED 165Hz', Processor: 'Snapdragon 8 Gen 3', RAM: '16GB', Storage: '256GB', Battery: '5500 mAh', 'Rear Camera': '50MP Triple', Weight: '225g', '5G': 'Yes' } },
{ id: 33, name: 'ASUS ROG Phone 8 Pro', brand: 'ASUS', category: 'Smartphones', year: 2024, price: 1299, rating: 4.5, reviews: 1120,
  features: ['Rear AMOLED display', '24GB of RAM', '165Hz gaming display', 'AeroActive cooling accessory support'],
  pros: ['Enormous RAM and storage headroom', 'Rear display adds real utility', 'Exceptional sustained gaming performance'],
  cons: ['Among the most expensive Android phones', 'Overkill for non-gamers'],
  specs: { Display: '6.78" AMOLED 165Hz', Processor: 'Snapdragon 8 Gen 3', RAM: '24GB', Storage: '1TB', Battery: '5500 mAh', 'Rear Camera': '50MP Triple', Weight: '225g', '5G': 'Yes' } },
{ id: 34, name: 'Sony Xperia 1 VI', brand: 'Sony', category: 'Smartphones', year: 2024, price: 1399, rating: 4.2, reviews: 980,
  features: ['Variable telephoto zoom lens', 'Pro-level camera app', '4K 120fps video recording', 'Dedicated shutter button'],
  pros: ['True optical zoom versatility', 'Photography controls feel like a real camera', 'Excellent video recording quality'],
  cons: ['Very expensive for the market share', 'Software update pace is inconsistent'],
  specs: { Display: '6.5" OLED 120Hz', Processor: 'Snapdragon 8 Gen 3', RAM: '12GB', Storage: '256GB', Battery: '5000 mAh', 'Rear Camera': '48MP Triple', Weight: '192g', '5G': 'Yes' } },
{ id: 35, name: 'Sony Xperia 10 VI', brand: 'Sony', category: 'Smartphones', year: 2024, price: 499, rating: 4.0, reviews: 1340,
  features: ['Compact 21:9 display', 'Triple-camera system', 'Large 5000mAh battery', 'Dedicated Google Assistant button'],
  pros: ['Genuinely pocketable, one-hand size', 'Long battery life for a mid-ranger', 'Clean, close-to-stock Android'],
  cons: ['Only 60Hz refresh rate', 'Mid-range performance ceiling'],
  specs: { Display: '6.1" OLED', Processor: 'Snapdragon 6 Gen 1', RAM: '8GB', Storage: '128GB', Battery: '5000 mAh', 'Rear Camera': '48MP Triple', Weight: '164g', '5G': 'Yes' } },

/* ---------------------------- Laptops (36–70) ---------------------------- */
{ id: 36, name: 'MacBook Air M1', brand: 'Apple', category: 'Laptops', year: 2020, price: 999, rating: 4.7, reviews: 21340,
  features: ['Fanless M1 chip', 'All-day battery life', 'Retina display', 'Touch ID'],
  pros: ['Still remarkably fast for the price', 'Silent, fanless operation', 'Exceptional battery life'],
  cons: ['Only two Thunderbolt ports', '720p webcam feels dated'],
  specs: { Display: '13.3" Retina', Processor: 'Apple M1', RAM: '8GB', Storage: '256GB', 'Battery Life': '18 hours', GPU: '7-core Apple GPU', Weight: '1290g' } },
{ id: 37, name: 'MacBook Air M2', brand: 'Apple', category: 'Laptops', year: 2022, price: 1199, rating: 4.7, reviews: 14320,
  features: ['Redesigned flat chassis', 'MagSafe charging', '1080p webcam', 'Bigger Liquid Retina display'],
  pros: ['Sleeker, more modern design', 'Improved webcam and speakers', 'Strong everyday performance'],
  cons: ['Can throttle under sustained heavy loads', 'Base storage feels tight'],
  specs: { Display: '13.6" Liquid Retina', Processor: 'Apple M2', RAM: '8GB', Storage: '256GB', 'Battery Life': '18 hours', GPU: '8-core Apple GPU', Weight: '1240g' } },
{ id: 38, name: 'MacBook Air M3', brand: 'Apple', category: 'Laptops', year: 2024, price: 1099, rating: 4.8, reviews: 6540,
  features: ['M3 chip', 'Support for two external displays', 'Wi-Fi 6E', 'MagSafe charging'],
  pros: ['Excellent performance-per-watt', 'Now drives two external monitors', 'Same great fanless design'],
  cons: ['Base 8GB RAM is limiting for pros', 'Display refresh rate is only 60Hz'],
  specs: { Display: '13.6" Liquid Retina', Processor: 'Apple M3', RAM: '8GB', Storage: '256GB', 'Battery Life': '18 hours', GPU: '10-core Apple GPU', Weight: '1240g' } },
{ id: 39, name: 'MacBook Pro 13" M2', brand: 'Apple', category: 'Laptops', year: 2022, price: 1299, rating: 4.4, reviews: 5230,
  features: ['Touch Bar', 'M2 chip', 'Studio-quality mic array', 'Active cooling for sustained tasks'],
  pros: ['Handles sustained workloads better than the Air', 'Very long battery life', 'Familiar, reliable design'],
  cons: ['Dated design with thick bezels', 'Only two Thunderbolt ports'],
  specs: { Display: '13.3" Retina', Processor: 'Apple M2', RAM: '8GB', Storage: '256GB', 'Battery Life': '20 hours', GPU: '10-core Apple GPU', Weight: '1400g' } },
{ id: 40, name: 'MacBook Pro 14" M3', brand: 'Apple', category: 'Laptops', year: 2023, price: 1599, rating: 4.8, reviews: 9820,
  features: ['M3 chip', 'Liquid Retina XDR display', 'Up to 22-hour battery', 'Six-speaker sound system'],
  pros: ['Exceptional performance per watt', 'Stunning XDR display', 'Excellent battery life'],
  cons: ['Expensive RAM and storage upgrades', 'Limited port selection'],
  specs: { Display: '14.2" Liquid Retina XDR', Processor: 'Apple M3', RAM: '8GB', Storage: '512GB', 'Battery Life': '22 hours', GPU: '10-core Apple GPU', Weight: '1550g' } },
{ id: 41, name: 'MacBook Pro 16" M3 Max', brand: 'Apple', category: 'Laptops', year: 2023, price: 3499, rating: 4.8, reviews: 3120,
  features: ['M3 Max chip', 'Studio-grade thermal design', '16.2-inch XDR display', 'Six-speaker sound system'],
  pros: ['Workstation-class performance in a laptop', 'Gorgeous, colour-accurate display', 'Handles pro workloads without throttling'],
  cons: ['Very expensive', 'Heavy for a "portable" laptop'],
  specs: { Display: '16.2" Liquid Retina XDR', Processor: 'Apple M3 Max', RAM: '36GB', Storage: '1TB', 'Battery Life': '22 hours', GPU: '40-core Apple GPU', Weight: '2160g' } },
{ id: 42, name: 'Dell XPS 13', brand: 'Dell', category: 'Laptops', year: 2023, price: 999, rating: 4.4, reviews: 6210,
  features: ['InfinityEdge display', 'Zero-lattice keyboard', 'Capacitive touch function row', 'CNC aluminium chassis'],
  pros: ['Gorgeous, compact design', 'Premium build in a small footprint', 'Sharp InfinityEdge display'],
  cons: ['Limited port selection needs dongles', 'Capacitive function row takes adjustment'],
  specs: { Display: '13.4" FHD+', Processor: 'Intel i5-1330U', RAM: '8GB', Storage: '512GB', 'Battery Life': '12 hours', GPU: 'Intel Iris Xe', Weight: '1170g' } },
{ id: 43, name: 'Dell XPS 15', brand: 'Dell', category: 'Laptops', year: 2023, price: 1499, rating: 4.5, reviews: 5433,
  features: ['InfinityEdge display', 'NVIDIA RTX graphics', 'Premium CNC aluminium chassis', 'Optional 4K OLED panel'],
  pros: ['Gorgeous OLED display option', 'Strong creative performance', 'Sleek premium design'],
  cons: ['Battery life trails Apple silicon', 'Can run warm under load'],
  specs: { Display: '15.6" FHD+', Processor: 'Intel i7-13700H', RAM: '16GB', Storage: '512GB', 'Battery Life': '13 hours', GPU: 'RTX 4050', Weight: '1860g' } },
{ id: 44, name: 'Dell XPS 13 Plus', brand: 'Dell', category: 'Laptops', year: 2023, price: 1249, rating: 4.2, reviews: 2870,
  features: ['Edge-to-edge capacitive keyboard', 'Invisible haptic trackpad', 'Seamless glass palm rest', 'Zero-lattice keys'],
  pros: ['Strikingly minimal, futuristic design', 'Fast, responsive performance', 'Excellent display quality'],
  cons: ['Learning curve for the capacitive controls', 'Battery life is merely average'],
  specs: { Display: '13.4" FHD+', Processor: 'Intel i7-1360P', RAM: '16GB', Storage: '512GB', 'Battery Life': '11 hours', GPU: 'Intel Iris Xe', Weight: '1240g' } },
{ id: 45, name: 'Dell Inspiron 15', brand: 'Dell', category: 'Laptops', year: 2023, price: 649, rating: 4.1, reviews: 4560,
  features: ['Backlit keyboard', 'Fingerprint reader', 'Large 15.6-inch display', 'Wi-Fi 6'],
  pros: ['Solid everyday performance for the price', 'Comfortable full-size keyboard', 'Generous 512GB storage'],
  cons: ['Plastic build feels less premium', 'Middling battery life'],
  specs: { Display: '15.6" FHD', Processor: 'Intel i5-1235U', RAM: '8GB', Storage: '512GB', 'Battery Life': '9 hours', GPU: 'Intel Iris Xe', Weight: '1650g' } },
{ id: 46, name: 'Dell Inspiron 14 2-in-1', brand: 'Dell', category: 'Laptops', year: 2023, price: 749, rating: 4.1, reviews: 2340,
  features: ['360-degree convertible hinge', 'Touchscreen with pen support', 'Backlit keyboard', 'Fast charging'],
  pros: ['Versatile 2-in-1 flexibility', 'Good value for a convertible', 'Comfortable typing experience'],
  cons: ['Display is not as sharp as premium rivals', 'Only average battery life'],
  specs: { Display: '14" FHD Touch', Processor: 'Intel i5-1335U', RAM: '8GB', Storage: '512GB', 'Battery Life': '10 hours', GPU: 'Intel Iris Xe', Weight: '1550g' } },
{ id: 47, name: 'Lenovo ThinkPad X1 Carbon', brand: 'Lenovo', category: 'Laptops', year: 2023, price: 1399, rating: 4.5, reviews: 4210,
  features: ['Military-grade durability', 'Legendary keyboard', 'Rapid Charge', 'Webcam privacy shutter'],
  pros: ['Best-in-class keyboard', 'Ultra-light and durable', 'Excellent for business use'],
  cons: ['Integrated graphics limit gaming', 'Display could be brighter'],
  specs: { Display: '14" WUXGA', Processor: 'Intel i7-1355U', RAM: '16GB', Storage: '512GB', 'Battery Life': '15 hours', GPU: 'Intel Iris Xe', Weight: '1120g' } },
{ id: 48, name: 'Lenovo ThinkPad T14', brand: 'Lenovo', category: 'Laptops', year: 2023, price: 1099, rating: 4.3, reviews: 3120,
  features: ['MIL-SPEC durability testing', 'Spill-resistant keyboard', 'Rapid Charge', 'Optional 4G LTE'],
  pros: ['Excellent value in the ThinkPad lineup', 'Sturdy, reliable build', 'Comfortable keyboard'],
  cons: ['Bulkier than the X1 Carbon', 'Base display is not very bright'],
  specs: { Display: '14" FHD', Processor: 'Intel i5-1335U', RAM: '16GB', Storage: '512GB', 'Battery Life': '12 hours', GPU: 'Intel Iris Xe', Weight: '1460g' } },
{ id: 49, name: 'Lenovo ThinkPad X1 Yoga', brand: 'Lenovo', category: 'Laptops', year: 2023, price: 1599, rating: 4.4, reviews: 1870,
  features: ['360-degree convertible design', 'Integrated garage pen', 'WUXGA touch display', 'Dolby Atmos speakers'],
  pros: ['ThinkPad durability in a 2-in-1 form', 'Built-in pen is genuinely convenient', 'Excellent keyboard for a convertible'],
  cons: ['Heavier than typical convertibles', 'Premium price for a 2-in-1'],
  specs: { Display: '14" WUXGA Touch', Processor: 'Intel i7-1365U', RAM: '16GB', Storage: '512GB', 'Battery Life': '13 hours', GPU: 'Intel Iris Xe', Weight: '1400g' } },
{ id: 50, name: 'Lenovo Yoga 9i', brand: 'Lenovo', category: 'Laptops', year: 2023, price: 1399, rating: 4.4, reviews: 2980,
  features: ['Rotating soundbar hinge', '4K OLED touchscreen', 'Included active pen', '2-in-1 convertible design'],
  pros: ['Stunning 4K OLED display', 'Distinctive rotating soundbar design', 'Premium materials throughout'],
  cons: ['4K OLED hurts battery life', 'Heavier than typical Ultrabooks'],
  specs: { Display: '14" 4K OLED Touch', Processor: 'Intel i7-1360P', RAM: '16GB', Storage: '1TB', 'Battery Life': '11 hours', GPU: 'Intel Iris Xe', Weight: '1400g' } },
{ id: 51, name: 'Lenovo Yoga Slim 7', brand: 'Lenovo', category: 'Laptops', year: 2023, price: 999, rating: 4.2, reviews: 1980,
  features: ['OLED display', 'AMD Ryzen 7000 series chip', 'Slim aluminium chassis', 'Rapid Charge'],
  pros: ['Vibrant OLED screen at a reasonable price', 'Strong integrated graphics performance', 'Sleek, portable design'],
  cons: ['Speakers are underwhelming', 'Limited port selection'],
  specs: { Display: '14" 2.8K OLED', Processor: 'Ryzen 7 7840U', RAM: '16GB', Storage: '512GB', 'Battery Life': '13 hours', GPU: 'AMD Radeon 780M', Weight: '1290g' } },
{ id: 52, name: 'ASUS Zenbook 14 OLED', brand: 'ASUS', category: 'Laptops', year: 2023, price: 899, rating: 4.3, reviews: 3450,
  features: ['2.8K OLED display', 'Harman Kardon speakers', 'Number pad on trackpad', 'Military-grade durability'],
  pros: ['Excellent OLED display for the price', 'Surprisingly good speakers', 'Great value overall'],
  cons: ['Battery life is only average', 'Fan can be audible under load'],
  specs: { Display: '14" 2.8K OLED', Processor: 'Intel i7-1355U', RAM: '16GB', Storage: '512GB', 'Battery Life': '12 hours', GPU: 'Intel Iris Xe', Weight: '1390g' } },
{ id: 53, name: 'ASUS Zenbook Pro 16X', brand: 'ASUS', category: 'Laptops', year: 2023, price: 1999, rating: 4.4, reviews: 1230,
  features: ['AAS Ultra cooling hinge', '4K OLED touch display', 'Physical dial control', 'RTX 4070 graphics'],
  pros: ['Serious creative performance', 'Stunning 4K OLED canvas', 'Innovative cooling hinge design'],
  cons: ['Heavy for a "creator" laptop', 'Battery life takes a big hit under load'],
  specs: { Display: '16" 4K OLED', Processor: 'Intel i9-13905H', RAM: '32GB', Storage: '1TB', 'Battery Life': '9 hours', GPU: 'RTX 4070', Weight: '2200g' } },
{ id: 54, name: 'ASUS Zenbook S 13 OLED', brand: 'ASUS', category: 'Laptops', year: 2024, price: 1199, rating: 4.5, reviews: 1670,
  features: ['Ultra-thin ceraluminum chassis', 'Intel Core Ultra with NPU', '2.8K OLED display', 'Wi-Fi 6E'],
  pros: ['Remarkably thin and light', 'Gorgeous OLED display', 'Strong efficiency from Core Ultra'],
  cons: ['Limited port selection', 'Speakers lack bass'],
  specs: { Display: '13.3" 2.8K OLED', Processor: 'Intel Core Ultra 7', RAM: '16GB', Storage: '1TB', 'Battery Life': '14 hours', GPU: 'Intel Arc Graphics', Weight: '1000g' } },
{ id: 55, name: 'ASUS Zenbook Duo', brand: 'ASUS', category: 'Laptops', year: 2023, price: 1699, rating: 4.1, reviews: 1120,
  features: ['Dual 2.8K OLED touchscreens', 'Detachable Bluetooth keyboard', 'Kickstand design', 'ASUS Pen included'],
  pros: ['Genuinely useful dual-screen multitasking', 'Both displays are gorgeous OLED panels', 'Versatile stand and keyboard setup'],
  cons: ['Battery life suffers running two displays', 'Steep learning curve for the workflow'],
  specs: { Display: '14" 2.8K OLED Dual', Processor: 'Intel i7-1360P', RAM: '16GB', Storage: '1TB', 'Battery Life': '9 hours', GPU: 'Intel Iris Xe', Weight: '1650g' } },
{ id: 56, name: 'ASUS ROG Zephyrus G14', brand: 'ASUS', category: 'Laptops', year: 2023, price: 1649, rating: 4.6, reviews: 3872,
  features: ['AniMe Matrix lid display', 'Ryzen 9 processor', '165Hz display', 'Compact gaming chassis'],
  pros: ['Powerful gaming performance in a small body', 'Great display options', 'Strong build quality'],
  cons: ['Fans get loud under load', 'Battery drains fast while gaming'],
  specs: { Display: '14" QHD+ 165Hz', Processor: 'Ryzen 9 8945HS', RAM: '16GB', Storage: '1TB', 'Battery Life': '10 hours', GPU: 'RTX 4060', Weight: '1720g' } },
{ id: 57, name: 'ASUS ROG Strix G16', brand: 'ASUS', category: 'Laptops', year: 2023, price: 1799, rating: 4.3, reviews: 2340,
  features: ['165Hz QHD display', 'Per-key RGB keyboard', 'Intel Core i9 processor', 'Advanced cooling system'],
  pros: ['High refresh QHD gaming display', 'Strong sustained gaming performance', 'Roomy keyboard and trackpad'],
  cons: ['Short battery life away from a charger', 'Bulky and heavy to carry around'],
  specs: { Display: '16" QHD 165Hz', Processor: 'Intel i9-13980HX', RAM: '16GB', Storage: '1TB', 'Battery Life': '7 hours', GPU: 'RTX 4070', Weight: '2500g' } },
{ id: 58, name: 'HP Spectre x360 14', brand: 'HP', category: 'Laptops', year: 2023, price: 1299, rating: 4.4, reviews: 4230,
  features: ['360-degree convertible hinge', 'Gem-cut design', 'Bang & Olufsen audio', 'Included stylus'],
  pros: ['Versatile 2-in-1 design', 'Premium gem-cut aesthetic', 'Great speakers'],
  cons: ['Middling battery under heavy use', 'Fingerprint-prone chassis'],
  specs: { Display: '13.5" 3K2K OLED', Processor: 'Intel i7-1355U', RAM: '16GB', Storage: '1TB', 'Battery Life': '12 hours', GPU: 'Intel Iris Xe', Weight: '1360g' } },
{ id: 59, name: 'HP Spectre x360 16', brand: 'HP', category: 'Laptops', year: 2023, price: 1599, rating: 4.3, reviews: 1980,
  features: ['Larger 16-inch OLED canvas', 'Discrete RTX graphics', 'Gem-cut design', 'Included active pen'],
  pros: ['Bigger OLED display for creative work', 'Discrete GPU adds real versatility', 'Elegant, premium design'],
  cons: ['Heavier than the 14-inch model', 'Battery life drops with the GPU active'],
  specs: { Display: '16" 3K2K OLED Touch', Processor: 'Intel i7-13700H', RAM: '16GB', Storage: '1TB', 'Battery Life': '11 hours', GPU: 'RTX 4050', Weight: '2000g' } },
{ id: 60, name: 'HP Envy x360 15', brand: 'HP', category: 'Laptops', year: 2023, price: 899, rating: 4.1, reviews: 2870,
  features: ['360-degree hinge', 'AMD Ryzen 7000 series', 'Fast charging', 'B&O audio tuning'],
  pros: ['Strong value 2-in-1', 'Solid battery life for the price', 'Good all-around performance'],
  cons: ['Display is not as sharp as premium rivals', 'Plastic build in places'],
  specs: { Display: '15.6" FHD Touch', Processor: 'Ryzen 7 7730U', RAM: '16GB', Storage: '512GB', 'Battery Life': '11 hours', GPU: 'AMD Radeon Graphics', Weight: '1750g' } },
{ id: 61, name: 'HP Envy 16', brand: 'HP', category: 'Laptops', year: 2023, price: 1099, rating: 4.2, reviews: 1560,
  features: ['Discrete RTX graphics', 'Large 2K display', 'Tilt-forward keyboard design', 'Quad speakers'],
  pros: ['Capable for light creative and gaming work', 'Roomy 16-inch display', 'Comfortable ergonomic keyboard'],
  cons: ['Bulky and heavy', 'Battery life is unremarkable'],
  specs: { Display: '16" 2K', Processor: 'Intel i7-13700H', RAM: '16GB', Storage: '1TB', 'Battery Life': '10 hours', GPU: 'RTX 4050', Weight: '2140g' } },
{ id: 62, name: 'Microsoft Surface Laptop 5', brand: 'Microsoft', category: 'Laptops', year: 2023, price: 999, rating: 4.3, reviews: 3120,
  features: ['PixelSense touchscreen', 'Alcantara or metal keyboard deck', 'Windows Hello face unlock', 'Omnisonic speakers'],
  pros: ['Excellent build quality and finish', 'Long battery life claims hold up well', 'Comfortable keyboard and trackpad'],
  cons: ['Limited port selection', 'Not very upgradeable'],
  specs: { Display: '13.5" PixelSense', Processor: 'Intel i5-1235U', RAM: '8GB', Storage: '512GB', 'Battery Life': '17 hours', GPU: 'Intel Iris Xe', Weight: '1290g' } },
{ id: 63, name: 'Microsoft Surface Laptop Studio 2', brand: 'Microsoft', category: 'Laptops', year: 2023, price: 2099, rating: 4.4, reviews: 980,
  features: ['Dynamic Woven hinge', 'Haptic touchpad', 'Surface Slim Pen support', 'Discrete RTX graphics'],
  pros: ['Uniquely versatile hinge for drawing and presenting', 'Strong creative performance', 'Premium build and display'],
  cons: ['Very expensive', 'Heavier than a typical laptop'],
  specs: { Display: '14.4" PixelSense Flow', Processor: 'Intel i7-13700H', RAM: '32GB', Storage: '1TB', 'Battery Life': '10 hours', GPU: 'RTX 4060', Weight: '1820g' } },
{ id: 64, name: 'Microsoft Surface Laptop Go 3', brand: 'Microsoft', category: 'Laptops', year: 2023, price: 799, rating: 4.0, reviews: 2340,
  features: ['Compact 12.4-inch touchscreen', 'Lightweight aluminium design', 'Fingerprint power button', 'Fast charging'],
  pros: ['Genuinely portable and light', 'Attractive, compact design', 'Good battery life for daily use'],
  cons: ['Storage feels tight at the base tier', 'Performance is modest for demanding tasks'],
  specs: { Display: '12.4" PixelSense', Processor: 'Intel i5-1235U', RAM: '8GB', Storage: '256GB', 'Battery Life': '15 hours', GPU: 'Intel Iris Xe', Weight: '1130g' } },
{ id: 65, name: 'Acer Swift Go 14', brand: 'Acer', category: 'Laptops', year: 2023, price: 749, rating: 4.1, reviews: 1670,
  features: ['2.8K OLED display', 'Fingerprint reader', 'Backlit keyboard', 'Wi-Fi 6E'],
  pros: ['Excellent OLED screen for the price', 'Solid everyday performance', 'Good value overall'],
  cons: ['Battery life is merely average', 'Build feels less premium than rivals'],
  specs: { Display: '14" 2.8K OLED', Processor: 'Intel i5-1335U', RAM: '16GB', Storage: '512GB', 'Battery Life': '10 hours', GPU: 'Intel Iris Xe', Weight: '1390g' } },
{ id: 66, name: 'Acer Swift X', brand: 'Acer', category: 'Laptops', year: 2023, price: 999, rating: 4.0, reviews: 1120,
  features: ['Discrete RTX graphics', '2.8K OLED display', 'Generous 1TB storage', 'Compact 14-inch chassis'],
  pros: ['Discrete GPU is rare at this price', 'Vivid OLED display', 'Great storage capacity for the money'],
  cons: ['Battery life drops noticeably with the GPU active', 'Fan noise under load'],
  specs: { Display: '14" 2.8K OLED', Processor: 'Ryzen 7 7735U', RAM: '16GB', Storage: '1TB', 'Battery Life': '9 hours', GPU: 'RTX 4050', Weight: '1400g' } },
{ id: 67, name: 'Acer Swift 3', brand: 'Acer', category: 'Laptops', year: 2022, price: 649, rating: 4.0, reviews: 2980,
  features: ['Aluminium unibody chassis', 'Fingerprint reader', 'Backlit keyboard', 'Fast charging'],
  pros: ['Reliable everyday performance', 'Sturdy aluminium build', 'Great value for a metal-clad Ultrabook'],
  cons: ['Display is not very bright', 'Speakers are thin-sounding'],
  specs: { Display: '14" FHD', Processor: 'Ryzen 5 5625U', RAM: '8GB', Storage: '512GB', 'Battery Life': '11 hours', GPU: 'AMD Radeon Graphics', Weight: '1250g' } },
{ id: 68, name: 'MSI Stealth 16', brand: 'MSI', category: 'Laptops', year: 2023, price: 2199, rating: 4.3, reviews: 890,
  features: ['240Hz QHD+ display', 'Per-key RGB keyboard', 'CNC aluminium chassis', 'Cooler Boost thermal system'],
  pros: ['Blisteringly fast refresh rate for competitive gaming', 'Sleek design that doesn\u2019t scream "gaming laptop"', 'Strong sustained performance'],
  cons: ['Short battery life away from a charger', 'Premium price for the specs'],
  specs: { Display: '16" QHD+ 240Hz', Processor: 'Intel i9-13900H', RAM: '32GB', Storage: '1TB', 'Battery Life': '7 hours', GPU: 'RTX 4070', Weight: '2100g' } },
{ id: 69, name: 'MSI Prestige 13 Evo', brand: 'MSI', category: 'Laptops', year: 2023, price: 1299, rating: 4.1, reviews: 1230,
  features: ['True Color display calibration', 'Compact 13.3-inch chassis', 'MSI Center productivity suite', 'Fast charging'],
  pros: ['Colour-accurate display out of the box', 'Lightweight and portable', 'Business-friendly design'],
  cons: ['Speakers are unremarkable', 'Limited port selection'],
  specs: { Display: '13.3" FHD+', Processor: 'Intel i7-1360P', RAM: '16GB', Storage: '512GB', 'Battery Life': '12 hours', GPU: 'Intel Iris Xe', Weight: '1200g' } },
{ id: 70, name: 'MSI Creator Z16', brand: 'MSI', category: 'Laptops', year: 2023, price: 2499, rating: 4.3, reviews: 760,
  features: ['True Pixel colour-accurate display', 'RTX Studio certification', '165Hz QHD+ panel', 'CNC aluminium chassis'],
  pros: ['Excellent for colour-critical creative work', 'Strong sustained performance for rendering', 'Premium, minimalist design'],
  cons: ['Very expensive', 'Battery life is modest under load'],
  specs: { Display: '16" QHD+ 165Hz', Processor: 'Intel i9-13900H', RAM: '32GB', Storage: '1TB', 'Battery Life': '8 hours', GPU: 'RTX 4070', Weight: '2100g' } },

/* ------------------------ Headphones & Earbuds (71–105) ------------------------ */
{ id: 71, name: 'AirPods (2nd gen)', brand: 'Apple', category: 'Headphones', year: 2019, price: 129, rating: 4.5, reviews: 45230,
  features: ['H1 chip', 'Hey Siri hands-free', 'Automatic ear detection', 'Charging case included'],
  pros: ['Effortless pairing with Apple devices', 'Reliable, lightweight everyday fit', 'Still very affordable'],
  cons: ['No noise cancellation', 'Fit is not secure for workouts'],
  specs: { Type: 'In-ear', 'Battery Life': '5 hours', 'Noise Cancelling': 'No', Bluetooth: '5.0', 'Driver Size': '11mm', Weight: '4g' } },
{ id: 72, name: 'AirPods (3rd gen)', brand: 'Apple', category: 'Headphones', year: 2021, price: 169, rating: 4.5, reviews: 28760,
  features: ['Spatial audio support', 'MagSafe charging case', 'Adaptive EQ', 'Sweat and water resistant'],
  pros: ['Improved sound over the 2nd gen', 'Comfortable open-fit design', 'Sweat resistance for workouts'],
  cons: ['Still no active noise cancellation', 'Open fit leaks sound at higher volumes'],
  specs: { Type: 'In-ear', 'Battery Life': '6 hours', 'Noise Cancelling': 'No', Bluetooth: '5.0', 'Driver Size': '11mm', Weight: '4g' } },
{ id: 73, name: 'AirPods Pro (1st gen)', brand: 'Apple', category: 'Headphones', year: 2021, price: 249, rating: 4.6, reviews: 38900,
  features: ['Active noise cancellation', 'Transparency mode', 'Adaptive EQ', 'MagSafe charging case'],
  pros: ['Secure, comfortable in-ear fit', 'Effective noise cancellation', 'Seamless Apple device switching'],
  cons: ['Touch stem controls take practice', 'Battery life trails some rivals'],
  specs: { Type: 'In-ear', 'Battery Life': '6 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.0', 'Driver Size': '11mm', Weight: '6g' } },
{ id: 74, name: 'AirPods Pro (2nd gen)', brand: 'Apple', category: 'Headphones', year: 2022, price: 249, rating: 4.7, reviews: 31200,
  features: ['Improved H2 chip ANC', 'Adaptive Transparency', 'Personalised Spatial Audio', 'Touch volume control on stem'],
  pros: ['Noticeably better noise cancellation than 1st gen', 'Touch-based volume control is handy', 'Excellent call quality'],
  cons: ['Premium price for earbuds', 'Case is easy to misplace'],
  specs: { Type: 'In-ear', 'Battery Life': '6 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '11mm', Weight: '6g' } },
{ id: 75, name: 'AirPods Max', brand: 'Apple', category: 'Headphones', year: 2020, price: 549, rating: 4.5, reviews: 9982,
  features: ['Spatial audio with head tracking', 'Digital Crown control', 'Seamless Apple ecosystem pairing', 'Adaptive EQ'],
  pros: ['Seamless integration with Apple devices', 'Premium materials', 'Excellent spatial audio'],
  cons: ['Very expensive', 'Heavier than most rivals'],
  specs: { Type: 'Over-ear', 'Battery Life': '20 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.0', 'Driver Size': '40mm', Weight: '385g' } },
{ id: 76, name: 'Sony WH-1000XM4', brand: 'Sony', category: 'Headphones', year: 2020, price: 349, rating: 4.7, reviews: 31200,
  features: ['Industry-leading ANC for its time', 'Speak-to-Chat', 'Multipoint pairing', 'Wearing detection'],
  pros: ['Still excellent noise cancellation years later', 'Very comfortable for long listening sessions', 'Frequently discounted for great value'],
  cons: ['Touch controls can be finicky', 'Folding hinge feels less premium than newer models'],
  specs: { Type: 'Over-ear', 'Battery Life': '30 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.0', 'Driver Size': '40mm', Weight: '254g' } },
{ id: 77, name: 'Sony WH-1000XM5', brand: 'Sony', category: 'Headphones', year: 2022, price: 399, rating: 4.8, reviews: 22190,
  features: ['Industry-leading ANC', '30-hour battery', 'Multipoint Bluetooth', 'Speak-to-Chat'],
  pros: ['Best-in-class noise cancelling', 'Excellent sound quality', 'Very comfortable for long wear'],
  cons: ['Non-folding hinge design', 'Touch controls can misfire'],
  specs: { Type: 'Over-ear', 'Battery Life': '30 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.2', 'Driver Size': '30mm', Weight: '250g' } },
{ id: 78, name: 'Sony WF-1000XM4', brand: 'Sony', category: 'Headphones', year: 2021, price: 279, rating: 4.6, reviews: 17650,
  features: ['Integrated Processor V1', 'Adaptive Sound Control', 'Speak-to-Chat', 'IPX4 water resistance'],
  pros: ['Exceptional sound quality for true wireless', 'Strong noise cancellation', 'Compact, comfortable case'],
  cons: ['Fit may not suit smaller ears', 'Touch controls take some learning'],
  specs: { Type: 'In-ear', 'Battery Life': '8 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.2', 'Driver Size': '6mm', Weight: '7g' } },
{ id: 79, name: 'Sony WF-1000XM5', brand: 'Sony', category: 'Headphones', year: 2023, price: 299, rating: 4.7, reviews: 12340,
  features: ['Smaller, more comfortable shell', 'Improved ANC processing', 'Multipoint connection', '360 Reality Audio support'],
  pros: ['More comfortable fit than the previous gen', 'Excellent noise cancellation', 'Rich, detailed sound'],
  cons: ['Case is larger than some rivals', 'Premium price for earbuds'],
  specs: { Type: 'In-ear', 'Battery Life': '8 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '8.4mm', Weight: '6g' } },
{ id: 80, name: 'Sony WH-CH720N', brand: 'Sony', category: 'Headphones', year: 2023, price: 149, rating: 4.3, reviews: 8920,
  features: ['Lightweight design', 'Dual noise sensor ANC', 'Multipoint pairing', 'Quick charge'],
  pros: ['Excellent ANC value at this price', 'Very light and comfortable', 'Long battery life'],
  cons: ['Build feels plasticky', 'Sound lacks the detail of pricier Sony models'],
  specs: { Type: 'Over-ear', 'Battery Life': '35 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.2', 'Driver Size': '30mm', Weight: '192g' } },
{ id: 81, name: 'Bose QuietComfort 45', brand: 'Bose', category: 'Headphones', year: 2021, price: 329, rating: 4.6, reviews: 19870,
  features: ['Aware and Quiet modes', 'TriPort acoustic architecture', 'Adjustable EQ', 'Auto-off timer'],
  pros: ['Extremely comfortable for all-day wear', 'Balanced, natural sound signature', 'Reliable, proven ANC performance'],
  cons: ['Design is largely unchanged from its predecessor', 'No wear detection sensors'],
  specs: { Type: 'Over-ear', 'Battery Life': '24 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.1', 'Driver Size': '40mm', Weight: '238g' } },
{ id: 82, name: 'Bose QuietComfort Earbuds', brand: 'Bose', category: 'Headphones', year: 2020, price: 279, rating: 4.3, reviews: 12100,
  features: ['CustomTune ANC calibration', 'Adjustable noise cancellation', 'IPX4 rating', 'Volume-optimised EQ'],
  pros: ['Class-leading ANC at launch', 'Rich, punchy sound', 'Secure, stable fit'],
  cons: ['Bulkier than most true wireless earbuds', 'Shorter battery life than rivals'],
  specs: { Type: 'In-ear', 'Battery Life': '6 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.1', 'Driver Size': '9.3mm', Weight: '8.5g' } },
{ id: 83, name: 'Bose QuietComfort Earbuds II', brand: 'Bose', category: 'Headphones', year: 2022, price: 299, rating: 4.5, reviews: 14560,
  features: ['CustomTune ANC calibration', 'Smaller, refined design', 'Touch and app controls', 'IPX4 rating'],
  pros: ['Noticeably improved ANC over the original', 'More comfortable, refined fit', 'Excellent sound clarity'],
  cons: ['Still bulkier than some competitors', 'Battery life trails rivals'],
  specs: { Type: 'In-ear', 'Battery Life': '6 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '9.3mm', Weight: '6g' } },
{ id: 84, name: 'Bose QuietComfort Ultra', brand: 'Bose', category: 'Headphones', year: 2023, price: 429, rating: 4.7, reviews: 14032,
  features: ['Immersive Audio spatial sound', 'CustomTune calibration', 'Adjustable ANC', 'Plush ear cushions'],
  pros: ['Supremely comfortable fit', 'Excellent noise cancelling', 'Rich, immersive sound'],
  cons: ['Pricier than rivals', 'Shorter battery life than competitors'],
  specs: { Type: 'Over-ear', 'Battery Life': '24 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '35mm', Weight: '254g' } },
{ id: 85, name: 'Bose Ultra Open Earbuds', brand: 'Bose', category: 'Headphones', year: 2024, price: 299, rating: 4.1, reviews: 3450,
  features: ['Open-ear design', 'OpenAudio sound technology', 'Secure clip-on fit', 'IPX4 rating'],
  pros: ['Stay aware of your surroundings', 'Genuinely comfortable for long wear', 'Surprisingly rich bass for an open design'],
  cons: ['No noise cancellation by design', 'Premium price for the category'],
  specs: { Type: 'In-ear', 'Battery Life': '7.5 hours', 'Noise Cancelling': 'No', Bluetooth: '5.3', 'Driver Size': '9.3mm', Weight: '6.8g' } },
{ id: 86, name: 'Beats Studio3 Wireless', brand: 'Beats', category: 'Headphones', year: 2017, price: 199, rating: 4.3, reviews: 22340,
  features: ['Pure ANC', 'Apple W1 chip', 'Fast Fuel charging', 'Balanced Beats sound signature'],
  pros: ['Still a solid value years later', 'Punchy, fun sound signature', 'Easy pairing with Apple devices'],
  cons: ['Bluetooth version is behind current standards', 'Design feels dated next to newer models'],
  specs: { Type: 'Over-ear', 'Battery Life': '22 hours', 'Noise Cancelling': 'Yes', Bluetooth: '4.2', 'Driver Size': '40mm', Weight: '260g' } },
{ id: 87, name: 'Beats Studio Pro', brand: 'Beats', category: 'Headphones', year: 2023, price: 349, rating: 4.4, reviews: 8760,
  features: ['Personalised Spatial Audio', 'USB-C lossless audio', 'Adaptive ANC', 'Apple and Android feature parity'],
  pros: ['Refined, more balanced sound than past Beats', 'Works equally well with iOS and Android', 'Solid battery life'],
  cons: ['Case and cable feel like an afterthought', 'Noise cancellation trails class leaders'],
  specs: { Type: 'Over-ear', 'Battery Life': '24 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '40mm', Weight: '260g' } },
{ id: 88, name: 'Beats Fit Pro', brand: 'Beats', category: 'Headphones', year: 2021, price: 199, rating: 4.5, reviews: 16780,
  features: ['Adjustable wingtip fit', 'Active noise cancellation', 'Apple H1 chip', 'Spatial audio support'],
  pros: ['Wingtips give a genuinely secure workout fit', 'Strong ANC for the category', 'Great for both iOS and Android'],
  cons: ['Case is bulkier than AirPods Pro', 'Stem-free touch controls are easy to mispress'],
  specs: { Type: 'In-ear', 'Battery Life': '6 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.0', 'Driver Size': '9.5mm', Weight: '5.6g' } },
{ id: 89, name: 'Beats Powerbeats Pro', brand: 'Beats', category: 'Headphones', year: 2019, price: 249, rating: 4.4, reviews: 21230,
  features: ['Adjustable ear hooks', 'Apple H1 chip', 'Sweat and water resistance', 'On-ear volume and track controls'],
  pros: ['Ear hooks stay locked in during intense workouts', 'Long battery life for true wireless', 'Physical buttons are easy to use blind'],
  cons: ['No noise cancellation', 'Bulky charging case'],
  specs: { Type: 'In-ear', 'Battery Life': '9 hours', 'Noise Cancelling': 'No', Bluetooth: '5.0', 'Driver Size': '9mm', Weight: '10.3g' } },
{ id: 90, name: 'Beats Solo Buds', brand: 'Beats', category: 'Headphones', year: 2024, price: 79, rating: 4.0, reviews: 4230,
  features: ['Featherweight design', '18-hour single-charge battery', 'Compact pocket-friendly case', 'Fast Fuel charging'],
  pros: ['Exceptional battery life for the price', 'Very light and comfortable', 'Budget-friendly entry point'],
  cons: ['No active noise cancellation', 'Fixed-fit tips may not suit every ear'],
  specs: { Type: 'In-ear', 'Battery Life': '18 hours', 'Noise Cancelling': 'No', Bluetooth: '5.3', 'Driver Size': '8mm', Weight: '4.6g' } },
{ id: 91, name: 'Samsung Galaxy Buds Pro', brand: 'Samsung', category: 'Headphones', year: 2021, price: 199, rating: 4.3, reviews: 14320,
  features: ['Intelligent ANC', '360 Audio with head tracking', 'IPX7 water resistance', 'Voice Detect auto-switching'],
  pros: ['Excellent value at its price point', 'Secure, comfortable in-ear fit', 'Strong integration with Galaxy phones'],
  cons: ['Battery life trails newer rivals', 'ANC less effective than premium competitors'],
  specs: { Type: 'In-ear', 'Battery Life': '5 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.0', 'Driver Size': '11mm', Weight: '6.3g' } },
{ id: 92, name: 'Samsung Galaxy Buds2 Pro', brand: 'Samsung', category: 'Headphones', year: 2022, price: 229, rating: 4.5, reviews: 11230,
  features: ['24-bit Hi-Fi audio', 'Intelligent ANC', 'Smaller, lighter design', 'IPX7 water resistance'],
  pros: ['Noticeably improved sound quality', 'Comfortable, lightweight fit', 'Deep Samsung ecosystem features'],
  cons: ['Battery life is only average', 'Case lacks wireless charging on base model'],
  specs: { Type: 'In-ear', 'Battery Life': '5 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '10mm', Weight: '5.5g' } },
{ id: 93, name: 'Samsung Galaxy Buds FE', brand: 'Samsung', category: 'Headphones', year: 2023, price: 99, rating: 4.2, reviews: 9870,
  features: ['Active noise cancellation at a budget price', '360 Audio support', 'IPX2 splash resistance', 'Touch controls'],
  pros: ['ANC at a genuinely affordable price', 'Comfortable, secure fit', 'Solid value for Galaxy owners'],
  cons: ['Sound quality trails the Pro models', 'Limited water resistance'],
  specs: { Type: 'In-ear', 'Battery Life': '6 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '8mm', Weight: '5.6g' } },
{ id: 94, name: 'Samsung Galaxy Buds3 Pro', brand: 'Samsung', category: 'Headphones', year: 2024, price: 249, rating: 4.5, reviews: 4120,
  features: ['Redesigned open-fit-style stem', 'Blade Design ear tips', 'Intelligent ANC', '24-bit Hi-Fi audio'],
  pros: ['Refined new design is more comfortable', 'Excellent noise cancellation', 'Rich, detailed sound'],
  cons: ['Premium price for true wireless', 'New case shape takes adjustment'],
  specs: { Type: 'In-ear', 'Battery Life': '6 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '10mm', Weight: '5.7g' } },
{ id: 95, name: 'Nothing Ear (2)', brand: 'Nothing', category: 'Headphones', year: 2023, price: 149, rating: 4.3, reviews: 6780,
  features: ['Transparent design', 'Hi-Res Audio support', 'Personalised ANC', 'Dual connection mode'],
  pros: ['Distinctive, eye-catching design', 'Excellent sound for the price', 'Effective adaptive ANC'],
  cons: ['Companion app can be inconsistent', 'Case is a bit slippery to hold'],
  specs: { Type: 'In-ear', 'Battery Life': '6.3 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '11.6mm', Weight: '4.5g' } },
{ id: 96, name: 'Nothing Ear (a)', brand: 'Nothing', category: 'Headphones', year: 2024, price: 99, rating: 4.3, reviews: 3980,
  features: ['Bold yellow transparent design', 'Active noise cancellation', 'Bass-enhanced driver', 'Fast pairing with Nothing phones'],
  pros: ['Exceptional value for ANC earbuds', 'Fun, punchy sound signature', 'Standout design at this price'],
  cons: ['Case build feels a little light', 'ANC is good but not class-leading'],
  specs: { Type: 'In-ear', 'Battery Life': '5.5 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '11mm', Weight: '4.6g' } },
{ id: 97, name: 'Nothing Ear (stick)', brand: 'Nothing', category: 'Headphones', year: 2023, price: 99, rating: 4.0, reviews: 2340,
  features: ['Open-ear stick design', 'Twist-to-adjust EQ', 'Lipstick-style charging case', 'Lightweight fit'],
  pros: ['Genuinely comfortable open fit', 'Fun, unique lipstick-case design', 'Good sound for an open-ear design'],
  cons: ['No noise cancellation', 'Open fit is not ideal for noisy environments'],
  specs: { Type: 'In-ear', 'Battery Life': '7 hours', 'Noise Cancelling': 'No', Bluetooth: '5.3', 'Driver Size': '12.6mm', Weight: '4.4g' } },
{ id: 98, name: 'JBL Tour Pro 2', brand: 'JBL', category: 'Headphones', year: 2023, price: 249, rating: 4.3, reviews: 5230,
  features: ['Smart Case with touchscreen display', 'Adaptive ANC', 'Personi-fi sound personalisation', 'Multipoint connection'],
  pros: ['Touchscreen case is a genuinely clever feature', 'Strong ANC performance', 'Punchy, JBL-tuned sound'],
  cons: ['Smart case adds bulk', 'App features can feel gimmicky'],
  specs: { Type: 'In-ear', 'Battery Life': '8 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '10mm', Weight: '5.7g' } },
{ id: 99, name: 'JBL Live 770NC', brand: 'JBL', category: 'Headphones', year: 2023, price: 199, rating: 4.2, reviews: 3450,
  features: ['Adaptive ANC', 'Massive 65-hour battery', 'Smart Talk auto-pause', 'Multipoint connection'],
  pros: ['Outstanding battery life', 'Comfortable for long wear', 'Bold, bass-forward sound'],
  cons: ['ANC trails premium rivals', 'Build materials feel budget-oriented'],
  specs: { Type: 'Over-ear', 'Battery Life': '65 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '40mm', Weight: '219g' } },
{ id: 100, name: 'JBL Tune 770NC', brand: 'JBL', category: 'Headphones', year: 2023, price: 99, rating: 4.1, reviews: 7650,
  features: ['Active noise cancellation at a budget price', 'Multipoint connection', 'Foldable design', 'JBL Headphones app EQ'],
  pros: ['ANC at a genuinely low price', 'Long battery life', 'Comfortable, lightweight fit'],
  cons: ['Noise cancellation is basic compared to premium models', 'Plasticky build'],
  specs: { Type: 'Over-ear', 'Battery Life': '44 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.3', 'Driver Size': '40mm', Weight: '220g' } },
{ id: 101, name: 'JBL Endurance Peak 3', brand: 'JBL', category: 'Headphones', year: 2022, price: 99, rating: 4.1, reviews: 6120,
  features: ['IP68 waterproof rating', 'Secure ear hook fit', 'Powerhook magnetic charging', 'Touch controls'],
  pros: ['Genuinely sweat and waterproof for tough workouts', 'Long battery life', 'Secure fit that will not fall out'],
  cons: ['No noise cancellation', 'Bulkier fit than standard earbuds'],
  specs: { Type: 'In-ear', 'Battery Life': '10 hours', 'Noise Cancelling': 'No', Bluetooth: '5.2', 'Driver Size': '6mm', Weight: '6.5g' } },
{ id: 102, name: 'Sennheiser Momentum 4', brand: 'Sennheiser', category: 'Headphones', year: 2022, price: 379, rating: 4.6, reviews: 5241,
  features: ['60-hour battery life', 'Adaptive ANC', 'Sound personalisation', 'Multipoint connectivity'],
  pros: ['Class-leading battery life', 'Balanced, audiophile-grade sound', 'Comfortable clamping force'],
  cons: ['Bulky folded size', 'Companion app can be finicky'],
  specs: { Type: 'Over-ear', 'Battery Life': '60 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.2', 'Driver Size': '42mm', Weight: '293g' } },
{ id: 103, name: 'Sennheiser Momentum True Wireless 2', brand: 'Sennheiser', category: 'Headphones', year: 2020, price: 279, rating: 4.4, reviews: 6540,
  features: ['Adaptive ANC', 'aptX audio support', 'Transparent hearing mode', 'Touch controls'],
  pros: ['Rich, detailed audiophile sound', 'Effective adjustable ANC', 'Premium materials and finish'],
  cons: ['Case is large compared to rivals', 'Touch controls are sensitive to accidental taps'],
  specs: { Type: 'In-ear', 'Battery Life': '7 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.2', 'Driver Size': '7mm', Weight: '6g' } },
{ id: 104, name: 'Sennheiser Momentum True Wireless 3', brand: 'Sennheiser', category: 'Headphones', year: 2022, price: 249, rating: 4.5, reviews: 5980,
  features: ['Smaller, lighter shell', 'Adaptive ANC', 'Sound Personalisation', 'Wireless charging case'],
  pros: ['Much more comfortable fit than the 2nd gen', 'Excellent sound clarity and detail', 'Effective noise cancellation'],
  cons: ['Touch controls still take some getting used to', 'Case is still on the larger side'],
  specs: { Type: 'In-ear', 'Battery Life': '7 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.2', 'Driver Size': '7mm', Weight: '4.5g' } },
{ id: 105, name: 'Sony WF-C700N', brand: 'Sony', category: 'Headphones', year: 2023, price: 119, rating: 4.2, reviews: 5670,
  features: ['Compact, lightweight design', 'Active noise cancellation', '360 Reality Audio support', 'Multipoint connection'],
  pros: ['ANC and Sony sound quality at a budget price', 'Very light, comfortable fit', 'Compact carrying case'],
  cons: ['Noise cancellation trails Sony\u2019s flagship models', 'Touch controls are a bit fiddly'],
  specs: { Type: 'In-ear', 'Battery Life': '7.5 hours', 'Noise Cancelling': 'Yes', Bluetooth: '5.2', 'Driver Size': '5.8mm', Weight: '5.4g' } },

/* ---------------------------- Smartwatches (106–125) ---------------------------- */
{ id: 106, name: 'Apple Watch Series 7', brand: 'Apple', category: 'Smartwatches', year: 2021, price: 399, rating: 4.6, reviews: 21340,
  features: ['Larger, edge-to-edge display', 'Fast charging', 'Crack-resistant front crystal', 'Blood oxygen sensor'],
  pros: ['Bigger, easier-to-read display', 'Fast charging is genuinely convenient', 'Mature, reliable watchOS experience'],
  cons: ['Battery still needs nightly charging', 'Requires an iPhone'],
  specs: { Display: '1.9" Always-On Retina', 'Battery Life': '18 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '32g' } },
{ id: 107, name: 'Apple Watch Series 8', brand: 'Apple', category: 'Smartwatches', year: 2022, price: 399, rating: 4.6, reviews: 15230,
  features: ['Temperature sensing', 'Crash detection', 'International roaming with cellular', 'Low Power Mode'],
  pros: ['New temperature sensor adds useful health data', 'Crash detection could be lifesaving', 'Consistent, reliable performance'],
  cons: ['Design is nearly identical to the Series 7', 'Battery life unchanged'],
  specs: { Display: '1.9" Always-On Retina', 'Battery Life': '18 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '32g' } },
{ id: 108, name: 'Apple Watch Series 9', brand: 'Apple', category: 'Smartwatches', year: 2023, price: 399, rating: 4.7, reviews: 18320,
  features: ['Double Tap gesture', 'S9 chip with on-device Siri', 'Always-On Retina display', 'Crash detection'],
  pros: ['Best smartwatch for iPhone users', 'Fast, responsive performance', 'Handy Double Tap control'],
  cons: ['Battery barely lasts a full day', 'Requires an iPhone'],
  specs: { Display: '1.9" Always-On Retina', 'Battery Life': '18 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '39g' } },
{ id: 109, name: 'Apple Watch SE (2nd gen)', brand: 'Apple', category: 'Smartwatches', year: 2022, price: 249, rating: 4.5, reviews: 12870,
  features: ['Crash detection', 'Fall detection', 'Family Setup support', 'Affordable entry point to watchOS'],
  pros: ['Most affordable way into the Apple Watch ecosystem', 'Still fast, capable performance', 'Great starter watch via Family Setup'],
  cons: ['No Always-On display', 'Missing blood oxygen and ECG sensors'],
  specs: { Display: '1.78" Retina', 'Battery Life': '18 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'No', Weight: '27g' } },
{ id: 110, name: 'Apple Watch Ultra', brand: 'Apple', category: 'Smartwatches', year: 2022, price: 799, rating: 4.7, reviews: 9870,
  features: ['Titanium case', 'Action Button', 'Dual-frequency GPS', 'Extended battery Low Power Mode'],
  pros: ['Rugged, adventure-ready build', 'Genuinely longer battery life', 'Precise dual-frequency GPS for outdoor sports'],
  cons: ['Large and heavy on smaller wrists', 'Expensive'],
  specs: { Display: '1.92" Always-On Retina', 'Battery Life': '36 hours', 'Water Resistance': '100m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '61g' } },
{ id: 111, name: 'Apple Watch Ultra 2', brand: 'Apple', category: 'Smartwatches', year: 2023, price: 799, rating: 4.8, reviews: 7650,
  features: ['Brighter 3000-nit display', 'S9 chip with Double Tap', 'Titanium case', 'Precision dual-frequency GPS'],
  pros: ['Brightest Apple Watch display yet', 'Double Tap adds one-hand convenience', 'Best-in-class build for outdoor use'],
  cons: ['Still large for smaller wrists', 'Premium price'],
  specs: { Display: '1.92" Always-On Retina', 'Battery Life': '36 hours', 'Water Resistance': '100m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '61g' } },
{ id: 112, name: 'Samsung Galaxy Watch 5', brand: 'Samsung', category: 'Smartwatches', year: 2022, price: 279, rating: 4.4, reviews: 9870,
  features: ['Sapphire crystal glass', 'Body composition analysis', 'Improved battery over Watch 4', 'Sleep coaching'],
  pros: ['Durable sapphire crystal display', 'Useful body composition tracking', 'Solid battery life for an AMOLED watch'],
  cons: ['Full features need a Samsung phone', 'No physical rotating bezel'],
  specs: { Display: '1.4" Super AMOLED', 'Battery Life': '30 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '33g' } },
{ id: 113, name: 'Samsung Galaxy Watch 5 Pro', brand: 'Samsung', category: 'Smartwatches', year: 2022, price: 449, rating: 4.4, reviews: 5230,
  features: ['Titanium case', 'Route workout tracking', 'Extended 80-hour battery mode', 'Rugged, adventure-ready build'],
  pros: ['Far better battery life than the standard Watch 5', 'Tougher titanium build', 'Route tracking is great for hikers'],
  cons: ['Bulkier and heavier', 'Premium pricing'],
  specs: { Display: '1.4" Super AMOLED', 'Battery Life': '80 hours', 'Water Resistance': '100m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '46g' } },
{ id: 114, name: 'Samsung Galaxy Watch 6', brand: 'Samsung', category: 'Smartwatches', year: 2023, price: 299, rating: 4.5, reviews: 7621,
  features: ['Rotating bezel navigation', 'Body composition analysis', 'Sleep coaching', 'Wear OS with Google apps'],
  pros: ['Great display quality', 'Useful health metrics', 'Works well with Android'],
  cons: ['Battery life is modest', 'Best features need a Samsung phone'],
  specs: { Display: '1.5" Super AMOLED', 'Battery Life': '30 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '33g' } },
{ id: 115, name: 'Samsung Galaxy Watch 6 Classic', brand: 'Samsung', category: 'Smartwatches', year: 2023, price: 399, rating: 4.5, reviews: 4980,
  features: ['Physical rotating bezel', 'Stainless steel case', 'Body composition analysis', 'Sleep coaching'],
  pros: ['Rotating bezel returns and it is satisfying to use', 'Classic, premium watch styling', 'Comprehensive health tracking suite'],
  cons: ['Noticeably heavier than the standard Watch 6', 'Same modest battery life'],
  specs: { Display: '1.5" Super AMOLED', 'Battery Life': '30 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '59g' } },
{ id: 116, name: 'Google Pixel Watch', brand: 'Google', category: 'Smartwatches', year: 2022, price: 349, rating: 4.2, reviews: 6540,
  features: ['Domed circular design', 'Fitbit activity tracking', 'Wear OS with Google apps', 'Crash detection'],
  pros: ['Genuinely beautiful, minimalist design', 'Deep Fitbit health integration', 'Smooth Wear OS experience'],
  cons: ['Battery life needs daily charging', 'Limited band compatibility'],
  specs: { Display: '1.2" AMOLED', 'Battery Life': '24 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '36g' } },
{ id: 117, name: 'Google Pixel Watch 2', brand: 'Google', category: 'Smartwatches', year: 2023, price: 349, rating: 4.3, reviews: 3542,
  features: ['Fitbit health tracking built-in', 'Safety check feature', 'Wear OS with Assistant', 'Continuous heart rate tracking'],
  pros: ['Clean, cohesive software', 'Solid safety features', 'Comfortable, compact design'],
  cons: ['Battery struggles with always-on display enabled', 'Limited band compatibility with gen 1'],
  specs: { Display: '1.2" AMOLED', 'Battery Life': '24 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '36g' } },
{ id: 118, name: 'Garmin Venu 3', brand: 'Garmin', category: 'Smartwatches', year: 2023, price: 449, rating: 4.6, reviews: 4103,
  features: ['Built-in workout coaching', 'Wheelchair mode', 'Up to 14-day battery', 'Sleep coaching with naps'],
  pros: ['Exceptional battery life', 'Excellent for serious athletes', 'Great outdoor GPS tracking'],
  cons: ['Limited app ecosystem', 'Interface less polished than Apple or Samsung'],
  specs: { Display: '1.4" AMOLED', 'Battery Life': '336 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '47g' } },
{ id: 119, name: 'Garmin Forerunner 265', brand: 'Garmin', category: 'Smartwatches', year: 2023, price: 449, rating: 4.7, reviews: 3210,
  features: ['Training readiness score', 'Vivid AMOLED display', 'Multi-band GPS', 'Running dynamics'],
  pros: ['Purpose-built for serious runners', 'Excellent multi-day battery for a running watch', 'Bright, crisp AMOLED display'],
  cons: ['Limited smartwatch features beyond fitness', 'App ecosystem is minimal'],
  specs: { Display: '1.3" AMOLED', 'Battery Life': '396 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '47g' } },
{ id: 120, name: 'Garmin Fenix 7', brand: 'Garmin', category: 'Smartwatches', year: 2022, price: 699, rating: 4.7, reviews: 5670,
  features: ['Solar charging lens', 'Multi-band GPS', 'Topographic maps', 'Rugged titanium bezel options'],
  pros: ['Exceptional battery life, especially with solar', 'Built to survive serious outdoor abuse', 'Comprehensive multi-sport tracking'],
  cons: ['Large and heavy on the wrist', 'Premium price'],
  specs: { Display: '1.3" MIP', 'Battery Life': '432 hours', 'Water Resistance': '100m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '73g' } },
{ id: 121, name: 'Garmin Instinct 2', brand: 'Garmin', category: 'Smartwatches', year: 2022, price: 349, rating: 4.5, reviews: 4320,
  features: ['Military-grade durability rating', 'Solar charging option', 'Multi-sport tracking', '28-day standard battery life'],
  pros: ['Nearly indestructible build', 'Battery can last weeks per charge', 'Great value for a rugged outdoor watch'],
  cons: ['Low-resolution display compared to AMOLED rivals', 'No touchscreen'],
  specs: { Display: '0.9" MIP', 'Battery Life': '672 hours', 'Water Resistance': '100m', GPS: 'Yes', 'Always-On Display': 'Yes', Weight: '53g' } },
{ id: 122, name: 'Fitbit Sense 2', brand: 'Fitbit', category: 'Smartwatches', year: 2022, price: 299, rating: 4.2, reviews: 6210,
  features: ['Stress management sensor', 'Skin temperature tracking', 'Google apps built-in', '6-day battery life'],
  pros: ['Long battery life', 'Strong stress and health tracking', 'Comfortable, lightweight design'],
  cons: ['App requires a subscription for full features', 'Slower interface than rivals'],
  specs: { Display: '1.58" AMOLED', 'Battery Life': '144 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'No', Weight: '41g' } },
{ id: 123, name: 'Fitbit Versa 4', brand: 'Fitbit', category: 'Smartwatches', year: 2022, price: 229, rating: 4.1, reviews: 5430,
  features: ['Built-in GPS', '40+ exercise modes', '6-day battery life', 'Daily Readiness Score'],
  pros: ['Great battery life for daily use', 'Lightweight and comfortable', 'Solid fitness tracking basics'],
  cons: ['Many features locked behind a subscription', 'Limited third-party app support'],
  specs: { Display: '1.58" AMOLED', 'Battery Life': '144 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'No', Weight: '37g' } },
{ id: 124, name: 'Fitbit Charge 6', brand: 'Fitbit', category: 'Smartwatches', year: 2023, price: 159, rating: 4.3, reviews: 8760,
  features: ['Built-in GPS', 'Google apps and Maps integration', 'YouTube Music controls', '7-day battery life'],
  pros: ['Excellent fitness tracker at a fair price', 'Genuinely useful Google integration', 'Long battery life'],
  cons: ['Small display limits smartwatch functionality', 'Some features require a Premium subscription'],
  specs: { Display: '1.04" AMOLED', 'Battery Life': '168 hours', 'Water Resistance': '50m', GPS: 'Yes', 'Always-On Display': 'No', Weight: '30g' } },
{ id: 125, name: 'Fitbit Inspire 3', brand: 'Fitbit', category: 'Smartwatches', year: 2022, price: 99, rating: 4.2, reviews: 9430,
  features: ['10-day battery life', 'Sleep profile tracking', '20+ exercise modes', 'Lightweight, low-profile design'],
  pros: ['Excellent battery life for a fitness band', 'Very light and unobtrusive', 'Affordable entry into fitness tracking'],
  cons: ['No built-in GPS', 'Small display shows limited information'],
  specs: { Display: '1.08" AMOLED', 'Battery Life': '240 hours', 'Water Resistance': '50m', GPS: 'No', 'Always-On Display': 'No', Weight: '19g' } },

/* ---------------------------- Tablets (126–150) ---------------------------- */
{ id: 126, name: 'iPad (8th gen)', brand: 'Apple', category: 'Tablets', year: 2020, price: 299, rating: 4.4, reviews: 18760,
  features: ['A12 Bionic chip', 'Apple Pencil (1st gen) support', 'Smart Keyboard support', 'Retina display'],
  pros: ['Still a great affordable everyday tablet', 'Reliable performance for browsing and media', 'Wide accessory compatibility'],
  cons: ['Base storage is very limited', 'Thick bezels feel dated'],
  specs: { Display: '10.2" Retina', Processor: 'Apple A12 Bionic', RAM: '3GB', Storage: '32GB', 'Battery Life': '10 hours', Weight: '490g' } },
{ id: 127, name: 'iPad (9th gen)', brand: 'Apple', category: 'Tablets', year: 2021, price: 329, rating: 4.5, reviews: 21340,
  features: ['A13 Bionic chip', 'Centre Stage front camera', 'Apple Pencil (1st gen) support', 'True Tone display'],
  pros: ['Great value for an everyday tablet', 'Centre Stage is great for video calls', 'Solid, dependable performance'],
  cons: ['Still uses the older Lightning port', 'Same dated bezel design'],
  specs: { Display: '10.2" Retina', Processor: 'Apple A13 Bionic', RAM: '3GB', Storage: '64GB', 'Battery Life': '10 hours', Weight: '487g' } },
{ id: 128, name: 'iPad (10th gen)', brand: 'Apple', category: 'Tablets', year: 2022, price: 449, rating: 4.5, reviews: 14320,
  features: ['Redesigned edge-to-edge display', 'USB-C charging', 'Landscape front camera', 'A14 Bionic chip'],
  pros: ['Modern, edge-to-edge redesign', 'USB-C is a welcome upgrade', 'Solid everyday performance'],
  cons: ['Apple Pencil support needs an adapter for the 1st-gen pencil', 'Base storage still limited'],
  specs: { Display: '10.9" Liquid Retina', Processor: 'Apple A14 Bionic', RAM: '4GB', Storage: '64GB', 'Battery Life': '10 hours', Weight: '477g' } },
{ id: 129, name: 'iPad Air (4th gen)', brand: 'Apple', category: 'Tablets', year: 2020, price: 599, rating: 4.6, reviews: 16230,
  features: ['A14 Bionic chip', 'Apple Pencil (2nd gen) support', 'Touch ID in the power button', 'USB-C charging'],
  pros: ['Excellent performance-to-price ratio at launch', 'Modern flat-edge design', 'Touch ID power button is convenient'],
  cons: ['Base storage is limiting', 'No ProMotion display'],
  specs: { Display: '10.9" Liquid Retina', Processor: 'Apple A14 Bionic', RAM: '4GB', Storage: '64GB', 'Battery Life': '10 hours', Weight: '458g' } },
{ id: 130, name: 'iPad Air (5th gen)', brand: 'Apple', category: 'Tablets', year: 2022, price: 599, rating: 4.7, reviews: 12870,
  features: ['M1 chip', 'Apple Pencil (2nd gen) support', '5G option available', 'Centre Stage front camera'],
  pros: ['M1 power at a mid-range price', 'Excellent for Split View multitasking', 'Great camera for video calls'],
  cons: ['Base storage remains tight', 'No ProMotion display'],
  specs: { Display: '10.9" Liquid Retina', Processor: 'Apple M1', RAM: '8GB', Storage: '64GB', 'Battery Life': '10 hours', Weight: '461g' } },
{ id: 131, name: 'iPad mini (5th gen)', brand: 'Apple', category: 'Tablets', year: 2019, price: 399, rating: 4.4, reviews: 9870,
  features: ['A12 Bionic chip', 'Apple Pencil (1st gen) support', 'Compact 7.9-inch size', 'True Tone display'],
  pros: ['Perfectly pocketable tablet size', 'Still capable for reading and browsing', 'Wide accessory support'],
  cons: ['Thick bezels and dated design', 'Base storage is very limited'],
  specs: { Display: '7.9" Retina', Processor: 'Apple A12 Bionic', RAM: '3GB', Storage: '64GB', 'Battery Life': '10 hours', Weight: '300g' } },
{ id: 132, name: 'iPad mini (6th gen)', brand: 'Apple', category: 'Tablets', year: 2021, price: 499, rating: 4.6, reviews: 13210,
  features: ['A15 Bionic chip', 'Apple Pencil (2nd gen) support', 'USB-C charging', 'Landscape stereo speakers'],
  pros: ['Perfect size for one-handed use', 'Surprisingly powerful for its size', 'Modern, bezel-light redesign'],
  cons: ['Base storage is limiting', 'Can show jelly-scrolling on fast swipes'],
  specs: { Display: '8.3" Liquid Retina', Processor: 'Apple A15 Bionic', RAM: '4GB', Storage: '64GB', 'Battery Life': '10 hours', Weight: '293g' } },
{ id: 133, name: 'iPad Pro 11" M2', brand: 'Apple', category: 'Tablets', year: 2022, price: 799, rating: 4.7, reviews: 10230,
  features: ['M2 chip', 'ProMotion 120Hz display', 'Apple Pencil hover support', 'Thunderbolt port'],
  pros: ['Desktop-class M2 performance', 'Buttery-smooth 120Hz ProMotion', 'More portable than the 12.9-inch model'],
  cons: ['Standard LCD, not mini-LED like the 12.9"', 'Very expensive with accessories'],
  specs: { Display: '11" Liquid Retina', Processor: 'Apple M2', RAM: '8GB', Storage: '128GB', 'Battery Life': '10 hours', Weight: '466g' } },
{ id: 134, name: 'iPad Pro 12.9" M2', brand: 'Apple', category: 'Tablets', year: 2022, price: 1099, rating: 4.8, reviews: 11200,
  features: ['M2 chip', 'Liquid Retina XDR mini-LED display', 'Apple Pencil hover support', 'Thunderbolt port'],
  pros: ['Best-in-class tablet performance', 'Gorgeous mini-LED display', 'Huge app and accessory ecosystem'],
  cons: ['Very expensive with accessories', 'iPadOS still limits multitasking'],
  specs: { Display: '12.9" Liquid Retina XDR', Processor: 'Apple M2', RAM: '8GB', Storage: '256GB', 'Battery Life': '10 hours', Weight: '682g' } },
{ id: 135, name: 'iPad Pro 11" M4', brand: 'Apple', category: 'Tablets', year: 2024, price: 999, rating: 4.8, reviews: 4230,
  features: ['M4 chip', 'Tandem OLED display', 'Thinnest Apple product ever', 'Apple Pencil Pro support'],
  pros: ['Stunning new tandem OLED display', 'Remarkably thin and light', 'Massive M4 performance headroom'],
  cons: ['Very expensive, especially with accessories', 'Overkill for casual users'],
  specs: { Display: '11" Ultra Retina XDR', Processor: 'Apple M4', RAM: '8GB', Storage: '256GB', 'Battery Life': '10 hours', Weight: '444g' } },
{ id: 136, name: 'iPad Pro 13" M4', brand: 'Apple', category: 'Tablets', year: 2024, price: 1299, rating: 4.8, reviews: 3670,
  features: ['M4 chip', 'Tandem OLED display', 'Apple Pencil Pro with squeeze gesture', 'Nano-texture glass option'],
  pros: ['Best tablet display available today', 'Exceptional M4 performance', 'Genuinely laptop-replacing power for many'],
  cons: ['Among the most expensive tablets on the market', 'iPadOS still holds back the pro-level hardware'],
  specs: { Display: '13" Ultra Retina XDR', Processor: 'Apple M4', RAM: '8GB', Storage: '256GB', 'Battery Life': '10 hours', Weight: '579g' } },
{ id: 137, name: 'Samsung Galaxy Tab S8', brand: 'Samsung', category: 'Tablets', year: 2022, price: 699, rating: 4.4, reviews: 5230,
  features: ['S Pen included', 'DeX desktop mode', '120Hz display', 'IP68 water resistance'],
  pros: ['S Pen included at no extra cost', 'Smooth 120Hz display', 'Genuinely useful DeX productivity mode'],
  cons: ['LCD panel trails AMOLED rivals', 'Base storage is limited'],
  specs: { Display: '11" LCD 120Hz', Processor: 'Snapdragon 8 Gen 1', RAM: '8GB', Storage: '128GB', 'Battery Life': '12 hours', Weight: '503g' } },
{ id: 138, name: 'Samsung Galaxy Tab S8 Ultra', brand: 'Samsung', category: 'Tablets', year: 2022, price: 1099, rating: 4.5, reviews: 3870,
  features: ['Massive 14.6-inch AMOLED display', 'Dual front cameras with auto-framing', 'S Pen included', 'DeX desktop mode'],
  pros: ['Enormous, gorgeous AMOLED canvas', 'Excellent for multitasking and DeX', 'S Pen included in the box'],
  cons: ['Very large and heavy for handheld use', 'Premium pricing'],
  specs: { Display: '14.6" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 1', RAM: '12GB', Storage: '256GB', 'Battery Life': '13 hours', Weight: '726g' } },
{ id: 139, name: 'Samsung Galaxy Tab S9', brand: 'Samsung', category: 'Tablets', year: 2023, price: 799, rating: 4.5, reviews: 4230,
  features: ['S Pen included', 'IP68 water resistance', '120Hz AMOLED display', 'DeX desktop mode'],
  pros: ['First S-series with proper water resistance', 'Vivid AMOLED display', 'S Pen included at no extra cost'],
  cons: ['Base storage is still limited', 'Accessories sold separately add up quickly'],
  specs: { Display: '11" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 2', RAM: '8GB', Storage: '128GB', 'Battery Life': '13 hours', Weight: '498g' } },
{ id: 140, name: 'Samsung Galaxy Tab S9+', brand: 'Samsung', category: 'Tablets', year: 2023, price: 999, rating: 4.5, reviews: 2980,
  features: ['S Pen included', 'IP68 water resistance', 'Larger 12.4-inch AMOLED', 'DeX desktop mode'],
  pros: ['Great middle ground between the S9 and Ultra', 'Gorgeous large AMOLED display', 'Strong multitasking performance'],
  cons: ['Premium pricing', 'Heavier than the standard S9'],
  specs: { Display: '12.4" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 2', RAM: '12GB', Storage: '256GB', 'Battery Life': '13 hours', Weight: '581g' } },
{ id: 141, name: 'Samsung Galaxy Tab S9 Ultra', brand: 'Samsung', category: 'Tablets', year: 2023, price: 1199, rating: 4.6, reviews: 4321,
  features: ['S Pen included', 'DeX desktop mode', 'Massive 14.6" AMOLED display', 'IP68 water resistance'],
  pros: ['Huge, vivid AMOLED display', 'Great for productivity with DeX', 'S Pen included in the box'],
  cons: ['Very large for one-handed use', 'Premium pricing'],
  specs: { Display: '14.6" AMOLED 120Hz', Processor: 'Snapdragon 8 Gen 2', RAM: '12GB', Storage: '256GB', 'Battery Life': '13 hours', Weight: '732g' } },
{ id: 142, name: 'Samsung Galaxy Tab S6 Lite', brand: 'Samsung', category: 'Tablets', year: 2022, price: 349, rating: 4.3, reviews: 6780,
  features: ['S Pen included', 'Compact 10.4-inch display', 'Expandable storage', 'Long battery life'],
  pros: ['S Pen included at a budget price', 'Great for note-taking and reading', 'Solid battery life'],
  cons: ['Only 60Hz LCD display', 'Performance limited for demanding apps'],
  specs: { Display: '10.4" LCD', Processor: 'Exynos 1280', RAM: '4GB', Storage: '128GB', 'Battery Life': '13 hours', Weight: '467g' } },
{ id: 143, name: 'Samsung Galaxy Tab A9+', brand: 'Samsung', category: 'Tablets', year: 2023, price: 219, rating: 4.1, reviews: 8340,
  features: ['Quad speakers tuned by Dolby Atmos', '90Hz display', 'Large 11-inch screen', 'Budget-friendly price'],
  pros: ['Excellent value for casual media consumption', 'Surprisingly good quad-speaker sound', 'Large display for the price'],
  cons: ['Performance limited for demanding apps', 'No S Pen support'],
  specs: { Display: '11" LCD 90Hz', Processor: 'Snapdragon 695', RAM: '4GB', Storage: '64GB', 'Battery Life': '12 hours', Weight: '480g' } },
{ id: 144, name: 'Lenovo Tab P11', brand: 'Lenovo', category: 'Tablets', year: 2022, price: 299, rating: 4.1, reviews: 3210,
  features: ['2K display', 'Quad JBL speakers', 'Optional keyboard and pen accessories', 'Kids Space mode'],
  pros: ['Sharp 2K display for the price', 'Solid quad-speaker audio', 'Good value for media and browsing'],
  cons: ['Mid-range performance ceiling', 'Software updates are infrequent'],
  specs: { Display: '11.5" 2K LCD', Processor: 'MediaTek Helio G99', RAM: '6GB', Storage: '128GB', 'Battery Life': '12 hours', Weight: '490g' } },
{ id: 145, name: 'Lenovo Tab P11 Plus', brand: 'Lenovo', category: 'Tablets', year: 2021, price: 269, rating: 4.0, reviews: 2340,
  features: ['2K display', 'Quad speakers with Dolby Atmos', 'Optional Precision Pen 2', 'Kids Space profiles'],
  pros: ['Good display sharpness for the price', 'Decent battery life', 'Solid budget option for families'],
  cons: ['Performance lags for demanding apps', 'Build quality feels basic'],
  specs: { Display: '11" 2K LCD', Processor: 'MediaTek Helio G90T', RAM: '4GB', Storage: '128GB', 'Battery Life': '12 hours', Weight: '490g' } },
{ id: 146, name: 'Lenovo Tab P12', brand: 'Lenovo', category: 'Tablets', year: 2023, price: 399, rating: 4.1, reviews: 1980,
  features: ['Large 12.7-inch 2.5K display', 'Quad JBL speakers', 'Optional keyboard and Precision Pen 3', 'Desktop mode'],
  pros: ['Big, sharp display for productivity and media', 'Strong quad-speaker sound', 'Good value versus premium rivals'],
  cons: ['LCD, not OLED', 'App optimisation weaker than iPad'],
  specs: { Display: '12.7" 2.5K LCD', Processor: 'MediaTek Kompanio 1300T', RAM: '8GB', Storage: '128GB', 'Battery Life': '12 hours', Weight: '571g' } },
{ id: 147, name: 'Lenovo Tab P12 Pro', brand: 'Lenovo', category: 'Tablets', year: 2023, price: 649, rating: 4.2, reviews: 1980,
  features: ['3K OLED display', 'Precision Pen 3 support', 'Quad JBL speakers', 'Desktop mode'],
  pros: ['Vibrant OLED screen', 'Strong multimedia experience', 'Good value versus premium rivals'],
  cons: ['App optimisation weaker than iPad', 'Software updates less frequent'],
  specs: { Display: '12.7" OLED', Processor: 'MediaTek Kompanio 1300T', RAM: '8GB', Storage: '256GB', 'Battery Life': '11 hours', Weight: '565g' } },
{ id: 148, name: 'Microsoft Surface Pro 8', brand: 'Microsoft', category: 'Tablets', year: 2021, price: 899, rating: 4.3, reviews: 4560,
  features: ['120Hz PixelSense display', 'Kickstand design', 'Thunderbolt 4', 'Windows Hello face unlock'],
  pros: ['Smooth 120Hz display is a nice touch', 'Runs full Windows desktop apps', 'Versatile kickstand design'],
  cons: ['Keyboard and pen sold separately', 'Battery life is only average'],
  specs: { Display: '13" PixelSense', Processor: 'Intel i5-1135G7', RAM: '8GB', Storage: '256GB', 'Battery Life': '14 hours', Weight: '891g' } },
{ id: 149, name: 'Microsoft Surface Pro 9', brand: 'Microsoft', category: 'Tablets', year: 2022, price: 999, rating: 4.4, reviews: 3890,
  features: ['Full Windows 11 experience', 'Detachable keyboard support', 'Kickstand design', 'Thunderbolt 4'],
  pros: ['Runs full desktop apps', 'Excellent for productivity', 'Versatile laptop replacement'],
  cons: ['Keyboard and pen sold separately', 'Middling battery life for the category'],
  specs: { Display: '13" PixelSense', Processor: 'Intel i5-1235U', RAM: '8GB', Storage: '256GB', 'Battery Life': '15.5 hours', Weight: '879g' } },
{ id: 150, name: 'Microsoft Surface Pro 10', brand: 'Microsoft', category: 'Tablets', year: 2024, price: 1099, rating: 4.4, reviews: 1450,
  features: ['Intel Core Ultra with NPU', 'Brighter, anti-reflective display', 'Improved 1440p front camera', 'Windows Studio Effects'],
  pros: ['Noticeably improved display brightness', 'Better battery efficiency from Core Ultra', 'Great front camera for video calls'],
  cons: ['Keyboard and pen still sold separately', 'Iterative rather than dramatic upgrade'],
  specs: { Display: '13" PixelSense', Processor: 'Intel Core Ultra 5', RAM: '8GB', Storage: '256GB', 'Battery Life': '16 hours', Weight: '895g' } }

];
